export interface Spoken { ne: string; en: string }

/** Latin letter names in Devanagari — for spelling out acronyms in Nepali TTS. */
export const LETTERS_NE: Record<string, string> = {
  A: "ए", B: "बी", C: "सी", D: "डी", E: "ई", F: "एफ", G: "जी", H: "एच", I: "आई", J: "जे", K: "के", L: "एल", M: "एम",
  N: "एन", O: "ओ", P: "पी", Q: "क्यु", R: "आर", S: "एस", T: "टी", U: "यु", V: "भी", W: "डब्लु", X: "एक्स", Y: "वाई", Z: "जेड",
};

/**
 * Acronyms that are read as a word, or have a conventional Nepali reading. Anything not here
 * is spelled letter by letter (≤4 letters) or kept as a word (≥5 letters with a vowel).
 */
export const ACRONYMS: Record<string, Spoken> = {
  NEPSE: { ne: "नेप्से", en: "nepsay" },
  SEBON: { ne: "सेबोन", en: "sebon" },
  NRB: { ne: "एन आर बी", en: "N R B" },
  NOC: { ne: "एन ओ सी", en: "N O C" },
  NEA: { ne: "एन ई ए", en: "N E A" },
  NTC: { ne: "एन टी सी", en: "N T C" },
  DHM: { ne: "डी एच एम", en: "D H M" },
  KMC: { ne: "के एम सी", en: "K M C" },
  CAN: { ne: "क्यान", en: "can" },
  CIAA: { ne: "अख्तियार", en: "C I double-A" },
  UML: { ne: "एमाले", en: "U M L" },
  CPN: { ne: "सी पी एन", en: "C P N" },
  RSP: { ne: "रास्वपा", en: "R S P" },
  RPP: { ne: "राप्रपा", en: "R P P" },
  PM: { ne: "प्रधानमन्त्री", en: "P M" },
  CM: { ne: "मुख्यमन्त्री", en: "C M" },
  MP: { ne: "सांसद", en: "M P" },
  CDO: { ne: "सी डी ओ", en: "C D O" },
  DSP: { ne: "डी एस पी", en: "D S P" },
  SSP: { ne: "एस एस पी", en: "S S P" },
  IGP: { ne: "आई जी पी", en: "I G P" },
  DIG: { ne: "डी आई जी", en: "D I G" },
  APF: { ne: "ए पी एफ", en: "A P F" },
  UN: { ne: "यु एन", en: "U N" },
  US: { ne: "यु एस", en: "U S" },
  USA: { ne: "यु एस ए", en: "U S A" },
  UK: { ne: "यु के", en: "U K" },
  EU: { ne: "ई यु", en: "E U" },
  UAE: { ne: "यु ए ई", en: "U A E" },
  WHO: { ne: "डब्लु एच ओ", en: "W H O" },
  IMF: { ne: "आई एम एफ", en: "I M F" },
  ADB: { ne: "ए डी बी", en: "A D B" },
  GDP: { ne: "जी डी पी", en: "G D P" },
  NGO: { ne: "एन जी ओ", en: "N G O" },
  INGO: { ne: "आई एन जी ओ", en: "I N G O" },
  SAARC: { ne: "सार्क", en: "sark" },
  BIMSTEC: { ne: "बिमस्टेक", en: "bimstec" },
  FIFA: { ne: "फिफा", en: "fifa" },
  ICC: { ne: "आई सी सी", en: "I C C" },
  IPL: { ne: "आई पी एल", en: "I P L" },
  NPL: { ne: "एन पी एल", en: "N P L" },
  ACC: { ne: "ए सी सी", en: "A C C" },
  NASA: { ne: "नासा", en: "nasa" },
  COVID: { ne: "कोभिड", en: "covid" },
  VAT: { ne: "भ्याट", en: "vat" },
  PAN: { ne: "प्यान", en: "pan" },
  TU: { ne: "टी यु", en: "T U" },
  KU: { ne: "के यु", en: "K U" },
  CEO: { ne: "सी ई ओ", en: "C E O" },
  MD: { ne: "एम डी", en: "M D" },
  AI: { ne: "ए आई", en: "A I" },
  IT: { ne: "आई टी", en: "I T" },
  EV: { ne: "ई भी", en: "E V" },
  OTP: { ne: "ओ टी पी", en: "O T P" },
  ATM: { ne: "ए टी एम", en: "A T M" },
  SIM: { ne: "सिम", en: "sim" },
  GPS: { ne: "जी पी एस", en: "G P S" },
  PCR: { ne: "पी सी आर", en: "P C R" },
  ICU: { ne: "आई सी यु", en: "I C U" },
  IPO: { ne: "आई पी ओ", en: "I P O" },
  FPO: { ne: "एफ पी ओ", en: "F P O" },
  NID: { ne: "एन आई डी", en: "N I D" },
  PSC: { ne: "लोकसेवा", en: "P S C" },
  NPR: { ne: "रुपैयाँ", en: "rupees" },
  USD: { ne: "अमेरिकी डलर", en: "US dollar" },
  INR: { ne: "भारतीय रुपैयाँ", en: "Indian rupees" },
  MW: { ne: "मेगावाट", en: "megawatts" },
  KW: { ne: "किलोवाट", en: "kilowatts" },
  GB: { ne: "जी बी", en: "G B" },
  MB: { ne: "एम बी", en: "M B" },
  TV: { ne: "टी भी", en: "T V" },
  FM: { ne: "एफ एम", en: "F M" },
  BS: { ne: "बिक्रम संवत्", en: "B S" },
  AD: { ne: "ई सं", en: "A D" },
  ISIS: { ne: "आई एस", en: "isis" },
  NATO: { ne: "नाटो", en: "nato" },
  OPEC: { ne: "ओपेक", en: "opec" },
  AQI: { ne: "ए क्यु आई", en: "A Q I" },
  PM25: { ne: "पी एम दुई दशमलव पाँच", en: "P M two point five" },
};

/** Abbreviations with a dot — expanded before anything else sees the dot. */
export const ABBREVIATIONS: Record<string, Spoken> = {
  "डा.": { ne: "डाक्टर", en: "Doctor" },
  "डा": { ne: "डाक्टर", en: "Doctor" },
  "प्रा.": { ne: "प्राध्यापक", en: "Professor" },
  "प्रा.डा.": { ne: "प्राध्यापक डाक्टर", en: "Professor Doctor" },
  "ई.": { ne: "इन्जिनियर", en: "Engineer" },
  "वि.सं.": { ne: "विक्रम संवत्", en: "Bikram Sambat" },
  "वि.स.": { ne: "विक्रम संवत्", en: "Bikram Sambat" },
  "ई.सं.": { ne: "इस्वी संवत्", en: "A D" },
  "सं.": { ne: "संवत्", en: "year" },
  "ना.प्र.": { ne: "नायब प्रमुख", en: "deputy chief" },
  "का.मु.": { ne: "कामु", en: "acting" },
  "प्र.म.": { ne: "प्रधानमन्त्री", en: "prime minister" },
  "मु.म.": { ne: "मुख्यमन्त्री", en: "chief minister" },
  "सा.प्र.": { ne: "साँझ पख", en: "evening" },
  "कि.मि.": { ne: "किलोमिटर", en: "kilometres" },
  "कि.मी.": { ne: "किलोमिटर", en: "kilometres" },
  "मि.": { ne: "मिटर", en: "metres" },
  "के.जी.": { ne: "केजी", en: "kilograms" },
  "मे.वा.": { ne: "मेगावाट", en: "megawatts" },
  "रु.": { ne: "रुपैयाँ", en: "rupees" },
  "रू.": { ne: "रुपैयाँ", en: "rupees" },
  "नं.": { ne: "नम्बर", en: "number" },
  "पृ.": { ne: "पृष्ठ", en: "page" },
  "Dr.": { ne: "डाक्टर", en: "Doctor" },
  "Dr": { ne: "डाक्टर", en: "Doctor" },
  "Prof.": { ne: "प्रोफेसर", en: "Professor" },
  "Mr.": { ne: "मिस्टर", en: "Mister" },
  "Mrs.": { ne: "मिसेस", en: "Missus" },
  "Ms.": { ne: "मिस", en: "Miz" },
  "St.": { ne: "सेन्ट", en: "Saint" },
  "No.": { ne: "नम्बर", en: "number" },
  "Rs.": { ne: "रुपैयाँ", en: "rupees" },
  "Rs": { ne: "रुपैयाँ", en: "rupees" },
  "Ltd.": { ne: "लिमिटेड", en: "Limited" },
  "Pvt.": { ne: "प्राइभेट", en: "Private" },
  "Govt.": { ne: "सरकार", en: "Government" },
  "approx.": { ne: "करिब", en: "approximately" },
  "e.g.": { ne: "जस्तै", en: "for example" },
  "i.e.": { ne: "अर्थात्", en: "that is" },
  "vs.": { ne: "विरुद्ध", en: "versus" },
  "vs": { ne: "विरुद्ध", en: "versus" },
  "etc.": { ne: "आदि", en: "et cetera" },
  "sq.": { ne: "वर्ग", en: "square" },
  "hrs.": { ne: "घण्टा", en: "hours" },
  "hrs": { ne: "घण्टा", en: "hours" },
  "a.m.": { ne: "बिहान", en: "a m" },
  "p.m.": { ne: "दिउँसो", en: "p m" },
};

/** Units that follow a number. Key is matched case-sensitively after optional space. */
export const UNITS: Record<string, Spoken & { plural?: string }> = {
  "km/h": { ne: "किलोमिटर प्रति घण्टा", en: "kilometres per hour" },
  "kmph": { ne: "किलोमिटर प्रति घण्टा", en: "kilometres per hour" },
  "km": { ne: "किलोमिटर", en: "kilometres" },
  "m": { ne: "मिटर", en: "metres" },
  "cm": { ne: "सेन्टिमिटर", en: "centimetres" },
  "mm": { ne: "मिलिमिटर", en: "millimetres" },
  "kg": { ne: "किलो", en: "kilograms" },
  "g": { ne: "ग्राम", en: "grams" },
  "mg": { ne: "मिलिग्राम", en: "milligrams" },
  "L": { ne: "लिटर", en: "litres" },
  "l": { ne: "लिटर", en: "litres" },
  "ltr": { ne: "लिटर", en: "litres" },
  "ml": { ne: "मिलिलिटर", en: "millilitres" },
  "°C": { ne: "डिग्री सेल्सियस", en: "degrees Celsius" },
  "℃": { ne: "डिग्री सेल्सियस", en: "degrees Celsius" },
  "°": { ne: "डिग्री", en: "degrees" },
  "MW": { ne: "मेगावाट", en: "megawatts" },
  "kW": { ne: "किलोवाट", en: "kilowatts" },
  "GW": { ne: "गिगावाट", en: "gigawatts" },
  "GB": { ne: "जी बी", en: "gigabytes" },
  "MB": { ne: "एम बी", en: "megabytes" },
  "Mbps": { ne: "एम बी पी एस", en: "megabits per second" },
  "ha": { ne: "हेक्टर", en: "hectares" },
  "sq km": { ne: "वर्ग किलोमिटर", en: "square kilometres" },
  "sq ft": { ne: "वर्ग फिट", en: "square feet" },
  "ft": { ne: "फिट", en: "feet" },
  "hrs": { ne: "घण्टा", en: "hours" },
  "hr": { ne: "घण्टा", en: "hours" },
  "min": { ne: "मिनेट", en: "minutes" },
  "sec": { ne: "सेकेन्ड", en: "seconds" },
  "µg/m³": { ne: "माइक्रोग्राम प्रति घनमिटर", en: "micrograms per cubic metre" },
  "ug/m3": { ne: "माइक्रोग्राम प्रति घनमिटर", en: "micrograms per cubic metre" },
  "mph": { ne: "माइल प्रति घण्टा", en: "miles per hour" },
  "bn": { ne: "अर्ब", en: "billion" },
  "mn": { ne: "मिलियन", en: "million" },
};

/** Bikram Sambat month aliases → index 0–11. */
export const BS_MONTHS: Array<{ ne: string; en: string; aliases: string[] }> = [
  { ne: "बैशाख", en: "Baisakh", aliases: ["बैशाख", "वैशाख", "बैसाख", "baisakh", "baishakh", "vaishakh"] },
  { ne: "जेठ", en: "Jestha", aliases: ["जेठ", "जेष्ठ", "ज्येष्ठ", "jestha", "jeth", "jyestha"] },
  { ne: "असार", en: "Asar", aliases: ["असार", "आषाढ", "आषाढ़", "asar", "ashadh", "asadh", "ashad"] },
  { ne: "साउन", en: "Shrawan", aliases: ["साउन", "श्रावण", "सावन", "shrawan", "sawan", "saun", "shravan"] },
  { ne: "भदौ", en: "Bhadra", aliases: ["भदौ", "भाद्र", "भादौ", "bhadra", "bhadau", "bhado"] },
  { ne: "असोज", en: "Asoj", aliases: ["असोज", "आश्विन", "आस्विन", "अशोज", "asoj", "ashwin", "aswin", "ashoj"] },
  { ne: "कात्तिक", en: "Kartik", aliases: ["कात्तिक", "कार्तिक", "कातिक", "kartik", "kattik", "karttik"] },
  { ne: "मंसिर", en: "Mangsir", aliases: ["मंसिर", "मार्ग", "मङ्सिर", "मङ्‌सिर", "mangsir", "marga", "mansir"] },
  { ne: "पुष", en: "Poush", aliases: ["पुष", "पौष", "पुस", "poush", "push", "paush", "pus"] },
  { ne: "माघ", en: "Magh", aliases: ["माघ", "magh"] },
  { ne: "फागुन", en: "Falgun", aliases: ["फागुन", "फाल्गुन", "falgun", "phagun", "fagun", "phalgun"] },
  { ne: "चैत", en: "Chaitra", aliases: ["चैत", "चैत्र", "chaitra", "chait"] },
];

export const AD_MONTHS: Array<{ ne: string; en: string; aliases: string[] }> = [
  { ne: "जनवरी", en: "January", aliases: ["january", "jan", "जनवरी", "जनवरि"] },
  { ne: "फेब्रुअरी", en: "February", aliases: ["february", "feb", "फेब्रुअरी", "फेब्रुवरी"] },
  { ne: "मार्च", en: "March", aliases: ["march", "mar", "मार्च"] },
  { ne: "अप्रिल", en: "April", aliases: ["april", "apr", "अप्रिल", "अप्रील"] },
  { ne: "मे", en: "May", aliases: ["may", "मे"] },
  { ne: "जुन", en: "June", aliases: ["june", "jun", "जुन"] },
  { ne: "जुलाई", en: "July", aliases: ["july", "jul", "जुलाई"] },
  { ne: "अगस्ट", en: "August", aliases: ["august", "aug", "अगस्ट", "अगस्त"] },
  { ne: "सेप्टेम्बर", en: "September", aliases: ["september", "sept", "sep", "सेप्टेम्बर", "सेप्टेंबर"] },
  { ne: "अक्टोबर", en: "October", aliases: ["october", "oct", "अक्टोबर", "अक्टुबर"] },
  { ne: "नोभेम्बर", en: "November", aliases: ["november", "nov", "नोभेम्बर", "नोवेम्बर"] },
  { ne: "डिसेम्बर", en: "December", aliases: ["december", "dec", "डिसेम्बर", "डिसेंबर"] },
];

export const WEEKDAYS: Array<{ ne: string; en: string }> = [
  { ne: "आइतबार", en: "Sunday" }, { ne: "सोमबार", en: "Monday" }, { ne: "मंगलबार", en: "Tuesday" }, { ne: "बुधबार", en: "Wednesday" },
  { ne: "बिहीबार", en: "Thursday" }, { ne: "शुक्रबार", en: "Friday" }, { ne: "शनिबार", en: "Saturday" },
];

export function monthIndex(word: string, table: typeof BS_MONTHS): number {
  const w = word.toLowerCase().replace(/\.$/, "");
  return table.findIndex((m) => m.aliases.includes(w));
}

/** Symbols read aloud when they stand alone between words. */
export const SYMBOLS: Record<string, Spoken> = {
  "&": { ne: "र", en: "and" },
  "+": { ne: "प्लस", en: "plus" },
  "=": { ne: "बराबर", en: "equals" },
  "@": { ne: "एट", en: "at" },
  "#": { ne: "ह्यासट्याग", en: "hashtag" },
  "%": { ne: "प्रतिशत", en: "percent" },
  "~": { ne: "करिब", en: "approximately" },
  "→": { ne: "देखि", en: "to" },
  "₹": { ne: "भारतीय रुपैयाँ", en: "Indian rupees" },
  "$": { ne: "डलर", en: "dollars" },
  "€": { ne: "युरो", en: "euros" },
  "£": { ne: "पाउन्ड", en: "pounds" },
};
