/**
 * Generate a TypeScript typed accessor for a set of env keys: an `interface`
 * plus a small runtime reader over `process.env` that fails fast on any missing
 * key.
 */

/** Options for {@link genTypes}. */
export interface GenTypesOptions {
  /** Interface name (default `Env`). */
  interfaceName?: string;
  /** Emit the runtime `readEnv()` + `env` accessor (default `true`). */
  accessor?: boolean;
}

function propName(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

/** Generate TypeScript source (as a string) for the given env keys. */
export function genTypes(keys: string[], opts: GenTypesOptions = {}): string {
  const name = opts.interfaceName ?? "Env";
  const accessor = opts.accessor ?? true;
  const uniq = [...new Set(keys)];

  const fields = uniq.map((k) => `  ${propName(k)}: string;`).join("\n");
  const list = uniq.map((k) => JSON.stringify(k)).join(", ");

  let out = `// Generated by lacspace-dotenv — do not edit by hand.\n`;
  out += `export interface ${name} {\n${fields || "  [key: string]: string;"}\n}\n`;

  if (accessor) {
    out += `\nconst REQUIRED = [${list}] as const;\n\n`;
    out += `/** Read and validate the required env vars, throwing on any missing one. */\n`;
    out += `export function readEnv(source: Record<string, string | undefined> = process.env): ${name} {\n`;
    out += `  const missing = REQUIRED.filter((k) => source[k] === undefined || source[k] === "");\n`;
    out += `  if (missing.length > 0) {\n`;
    out += `    throw new Error("Missing required environment variables: " + missing.join(", "));\n`;
    out += `  }\n`;
    out += `  return Object.fromEntries(REQUIRED.map((k) => [k, source[k]])) as unknown as ${name};\n`;
    out += `}\n\n`;
    out += `export const env: ${name} = readEnv();\n`;
  }
  return out;
}
