/**
 * Header-only detectors: bounce senders, bounce messages, auto-replies and
 * challenge-response mail.
 */

import { decodeEncodedWords, first, parseContentType, toHeaderMap } from "./mime";
import type { HeaderInput, HeaderMap } from "./mime";

export const ADDR_SRC = "[A-Za-z0-9._%+'=!#$&*/?^`{|}~-]+@[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?(?:\\.[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?)+";

/** Pull the bare address out of `"Name" <a@b>`, `<a@b>` or `a@b`. */
export function extractAddress(from: string | undefined | null): string | undefined {
  if (!from || typeof from !== "string") return undefined;
  const angle = /<([^<>]*)>/.exec(from);
  const src = angle ? (angle[1] ?? "") : from;
  const m = new RegExp(ADDR_SRC).exec(src);
  if (m) return m[0].toLowerCase();
  const bare = src.trim();
  return bare && !/\s/.test(bare) ? bare.toLowerCase() : undefined;
}

const BOUNCE_LOCAL =
  /^(mailer[-_.]?daemon|mail[-_.]?daemon|postmaster|mail[-_.]?delivery[-_.]?(system|subsystem)?|bounces?|bounces?[-+=_.].*|.*[-+_.]bounces?|ndr|nondeliver(y|able)?|returned[-_.]?mail)$/i;

/** True for mailer-daemon, postmaster, bounces@, bounce-*@ and similar senders. Accepts "Name <addr>". */
export function isBounceSender(from: string): boolean {
  try {
    if (!from || typeof from !== "string") return false;
    const addr = extractAddress(from);
    if (addr) {
      const at = addr.lastIndexOf("@");
      const local = at >= 0 ? addr.slice(0, at) : addr;
      if (BOUNCE_LOCAL.test(local)) return true;
    }
    return /\bmailer[- ]?daemon\b|\bmail delivery (system|subsystem)\b/i.test(from);
  } catch {
    return false;
  }
}

export const BOUNCE_SUBJECT_RE =
  /undeliver|undelivered mail|delivery status notification|mail delivery (failed|failure|subsystem|system|error|notification)|returned mail|returning message to sender|failure notice|delivery (has )?fail|delivery failure|could not be delivered|couldn't be delivered|address not found|non[- ]?delivery|nondeliverable|delivery notification|mail system error|returned to sender|message not delivered|delivery problem|delayed mail|warning: (message|could not)|delivery delayed|not delivered/i;

export function getSubject(h: HeaderMap): string {
  return decodeEncodedWords(first(h, "subject") ?? "").trim();
}

function reportType(h: HeaderMap): string {
  const ct = parseContentType(first(h, "content-type"));
  return ct.type === "multipart/report" ? (ct.params["report-type"] ?? "").toLowerCase() : "";
}

export function isBounceMap(h: HeaderMap): boolean {
  const rt = reportType(h);
  if (rt === "delivery-status" || rt === "feedback-report" || rt === "global-delivery-status") return true;
  if (h.has("x-failed-recipients")) return true;
  if (/^true$/i.test(first(h, "x-ms-exchange-message-is-ndr") ?? "x")) return true;
  const from = first(h, "from") ?? "";
  if (isBounceSender(from)) return true;
  const subject = getSubject(h);
  const nullSender = /^\s*<\s*>\s*$/.test(first(h, "return-path") ?? "x");
  if (BOUNCE_SUBJECT_RE.test(subject) && (nullSender || /^auto-(replied|generated)/i.test(first(h, "auto-submitted") ?? ""))) return true;
  return false;
}

/** True when the headers look like a delivery failure report or an ARF complaint report. */
export function isBounce(headers: HeaderInput): boolean {
  try {
    return isBounceMap(toHeaderMap(headers));
  } catch {
    return false;
  }
}

export const AUTO_REPLY_SUBJECT_RE =
  /^\s*(automatic reply|auto(matic)?[- ]?reply|auto[- ]?response|autoreply|auto[- ]?respond|out of (the )?office|ooo\b|on vacation|vacation (reply|response|notice)|away from (the )?office|i am (currently )?out of (the )?office|i'm (currently )?out of (the )?office|abwesenheitsnotiz|automatische antwort|réponse automatique|respuesta automática|risposta automatica|resposta automática|automatisch antwoord|afwezigheidsbericht)/i;

export function isAutoReplyMap(h: HeaderMap): boolean {
  const as = (first(h, "auto-submitted") ?? "").trim().toLowerCase();
  if (as && !as.startsWith("no")) return true;
  if (h.has("x-autoreply") && !/^\s*(no|false|0)\s*$/i.test(first(h, "x-autoreply") ?? "")) return true;
  if (h.has("x-autorespond")) return true;
  if (h.has("x-autoresponder")) return true;
  if (/^reply$/i.test((first(h, "x-autogenerated") ?? "").trim())) return true;
  if (h.has("x-ms-exchange-inbox-rules-loop")) return true;
  if (/^\s*auto[_-]reply\s*$/i.test(first(h, "precedence") ?? "")) return true;
  if (/^\s*(AutoReply|OOF)\s*$/i.test(first(h, "x-auto-response-suppress-type") ?? "")) return true;
  return AUTO_REPLY_SUBJECT_RE.test(getSubject(h));
}

/**
 * True for RFC 3834 auto-replies: Auto-Submitted (anything but "no"),
 * X-Autoreply, X-Autorespond, Precedence: auto_reply,
 * X-MS-Exchange-Inbox-Rules-Loop, or an out-of-office / "Automatic reply" subject.
 */
export function isAutoReply(headers: HeaderInput): boolean {
  try {
    return isAutoReplyMap(toHeaderMap(headers));
  } catch {
    return false;
  }
}

const CHALLENGE_STRONG =
  /verify (that )?(you('| a)?re|you are) (a )?(human|real person|not a (robot|bot))|prove (that )?(you('| a)?re|you are) (a )?(human|real person)|confirm (that )?(you('| a)?re|you are) (a )?(human|real person)|challenge[- ]response|sender verification (is )?required|verify your (email )?address (so|to|before)[^.\n]{0,40}deliver|\bboxbe\b|spamarrest|spam arrest|mailinblack|before (your|this) (message|email) (can be|is|will be) delivered[^.\n]{0,60}(verify|confirm|click)|(verify|confirm)[^.\n]{0,60}(to|so) (deliver|release) (your|the) (message|email)/i;

const CHALLENGE_WEAK =
  /whitelist|allow ?list|approved senders?|held (until|pending)|pending (verification|approval)|please (click|follow|visit) (the|this) link[^.\n]{0,40}(deliver|release|confirm|verify)/i;

/** Challenge-response ("verify you're human to deliver") detection. */
export function looksLikeChallenge(h: HeaderMap, text: string): boolean {
  const hay = `${getSubject(h)}\n${text.slice(0, 5000)}`;
  if (CHALLENGE_STRONG.test(hay)) return true;
  return CHALLENGE_WEAK.test(hay) && isAutoReplyMap(h);
}
