/**
 * Extra output formats — all **pure** string builders, no colour codes, so they
 * render the same in a file, a PR comment or a browser:
 *
 * - {@link formatMarkdown}  — a single-report Markdown summary (great as a PR comment).
 * - {@link formatHtml}      — a standalone, shareable HTML report.
 * - {@link formatSiteReport}/{@link formatSiteMarkdown} — the crawl-audit rollup.
 * - {@link formatLeaderboard} — the batch (`--input`) table.
 * - {@link formatRegressions} — a `--baseline` diff.
 */
import type { Category, Finding, Grade, Regression, Report, SiteReport } from "./types.js";

const ICON: Record<Finding["status"], string> = { ok: "✓", warn: "▲", fail: "✗", info: "ℹ" };

function badge(grade: Grade | null): string {
  return grade ? `\`${grade}\`` : "`–`";
}

// ---------------- Markdown (single report) ----------------

function mdFinding(f: Finding): string {
  const base = `- ${ICON[f.status]} ${f.message}`;
  const fix = f.fix && (f.status === "warn" || f.status === "fail") ? `\n  - **Fix:** ${f.fix}` : "";
  return base + fix;
}

/** Render a report as Markdown. `verbose` also lists passing checks. */
export function formatMarkdown(report: Report, verbose = false): string {
  const lines: string[] = [];
  lines.push(`## ◆ lacspace-inspect — ${badge(report.grade)} ${report.score}/100`);
  lines.push("");
  lines.push(`**URL:** ${report.url}  `);
  const meta: string[] = [];
  if (report.httpStatus) meta.push(`HTTP ${report.httpStatus}`);
  meta.push(report.https ? "HTTPS" : "HTTP");
  meta.push(`${(report.stats.htmlBytes / 1024).toFixed(0)} KB`);
  if (report.stats.responseTimeMs !== undefined) meta.push(`${report.stats.responseTimeMs} ms`);
  lines.push(`**Audited:** ${report.fetchedAt} · ${meta.join(" · ")}`);
  lines.push("");

  const fails = report.categories.flatMap((c) => c.findings).filter((f) => f.status === "fail").length;
  const warns = report.categories.flatMap((c) => c.findings).filter((f) => f.status === "warn").length;
  lines.push(`> **${fails} failing · ${warns} warning** — overall grade ${badge(report.grade)}`);
  lines.push("");

  lines.push("| Category | Grade | Score |");
  lines.push("| --- | :---: | ---: |");
  for (const c of report.categories) {
    lines.push(`| ${c.title} | ${badge(c.grade)} | ${c.score === null ? "–" : c.score} |`);
  }
  lines.push("");

  for (const c of report.categories) {
    const shown = c.findings.filter((f) => verbose || f.status !== "ok");
    if (shown.length === 0) continue;
    lines.push(`### ${c.title} ${badge(c.grade)}${c.score === null ? "" : ` — ${c.score}/100`}`);
    lines.push("");
    for (const f of shown) lines.push(mdFinding(f));
    lines.push("");
  }

  if (report.tech.length) {
    lines.push(`**Tech:** ${report.tech.join(", ")}`);
    lines.push("");
  }
  lines.push(`<sub>Generated by lacspace-inspect · static HTML audit, not a runtime Lighthouse pass.</sub>`);
  return lines.join("\n");
}

// ---------------- HTML (single report) ----------------

function esc(s: string): string {
  return s.replace(/[&<>"]/g, (ch) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[ch]!));
}
const GRADE_HEX: Record<Grade, string> = { A: "#16a34a", B: "#0891b2", C: "#ca8a04", D: "#ea580c", F: "#dc2626" };
function gradeHex(g: Grade | null): string { return g ? GRADE_HEX[g] : "#94a3b8"; }

/** Render a report as a standalone, shareable HTML document. Pure. */
export function formatHtml(report: Report, verbose = false): string {
  const fails = report.categories.flatMap((c) => c.findings).filter((f) => f.status === "fail").length;
  const warns = report.categories.flatMap((c) => c.findings).filter((f) => f.status === "warn").length;

  const cat = (c: Category): string => {
    const shown = c.findings.filter((f) => verbose || f.status !== "ok");
    const items = shown.map((f) => {
      const fix = f.fix && (f.status === "warn" || f.status === "fail")
        ? `<div class="fix"><b>Fix:</b> ${esc(f.fix)}</div>` : "";
      const detail = f.detail && f.status !== "ok" ? `<div class="detail">${esc(String(f.detail))}</div>` : "";
      return `<li class="s-${f.status}"><span class="ic">${ICON[f.status]}</span><div><div>${esc(f.message)}</div>${detail}${fix}</div></li>`;
    }).join("");
    const g = c.grade;
    return `<section class="card"><h3><span class="pill" style="background:${gradeHex(g)}">${g ?? "–"}</span> ${esc(c.title)} <span class="sc">${c.score === null ? "not graded" : c.score + "/100"}</span></h3><ul>${items || '<li class="s-ok"><span class="ic">✓</span><div>All checks pass</div></li>'}</ul></section>`;
  };

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>lacspace-inspect — ${esc(report.url)}</title>
<style>
:root{--bg:#f8fafc;--fg:#0f172a;--mut:#64748b;--card:#fff;--line:#e2e8f0}
@media(prefers-color-scheme:dark){:root{--bg:#0b1120;--fg:#e2e8f0;--mut:#94a3b8;--card:#111827;--line:#1f2937}}
*{box-sizing:border-box}body{margin:0;font:15px/1.55 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:var(--bg);color:var(--fg)}
.wrap{max-width:840px;margin:0 auto;padding:32px 20px}
.head{display:flex;align-items:center;gap:20px;flex-wrap:wrap}
.grade{font-weight:800;font-size:34px;color:#fff;width:70px;height:70px;border-radius:16px;display:flex;align-items:center;justify-content:center}
.url{font-weight:600;word-break:break-all}.meta{color:var(--mut);font-size:13px;margin-top:2px}
.sum{color:var(--mut);margin:14px 0 26px}
.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:16px 18px;margin:12px 0}
.card h3{margin:0 0 8px;font-size:16px;display:flex;align-items:center;gap:10px}
.pill{color:#fff;font-weight:700;border-radius:8px;padding:2px 9px;font-size:13px}
.sc{margin-left:auto;color:var(--mut);font-weight:500;font-size:13px}
ul{list-style:none;margin:0;padding:0}li{display:flex;gap:10px;padding:6px 0;border-top:1px dashed var(--line)}li:first-child{border-top:0}
.ic{width:16px;flex:0 0 16px;text-align:center}
.s-fail .ic{color:#dc2626}.s-warn .ic{color:#ca8a04}.s-ok .ic{color:#16a34a}.s-info .ic{color:#0891b2}
.fix{margin-top:4px;font-size:13px;color:var(--fg);background:rgba(148,163,184,.14);border-radius:8px;padding:6px 9px}
.detail{margin-top:3px;font-size:12px;color:var(--mut);white-space:pre-wrap}
.tech{color:var(--mut);font-size:13px;margin-top:16px}
footer{color:var(--mut);font-size:12px;margin-top:26px;text-align:center}
</style></head><body><div class="wrap">
<div class="head"><div class="grade" style="background:${gradeHex(report.grade)}">${report.grade}</div>
<div><div class="url">${esc(report.url)}</div><div class="meta">${report.score}/100 · ${report.httpStatus ? "HTTP " + report.httpStatus + " · " : ""}${report.https ? "HTTPS" : "HTTP"} · ${(report.stats.htmlBytes / 1024).toFixed(0)} KB${report.stats.responseTimeMs !== undefined ? " · " + report.stats.responseTimeMs + " ms" : ""}</div></div></div>
<p class="sum"><b>${fails}</b> failing · <b>${warns}</b> warning · audited ${esc(report.fetchedAt)}</p>
${report.categories.map(cat).join("\n")}
${report.tech.length ? `<div class="tech"><b>Tech:</b> ${report.tech.map(esc).join(", ")}</div>` : ""}
<footer>Generated by lacspace-inspect — static HTML audit, not a runtime Lighthouse pass.</footer>
</div></body></html>`;
}

// ---------------- Site (crawl) ----------------

/** Terminal-friendly (plain, no colour) crawl-audit summary. Pure. */
export function formatSiteReport(site: SiteReport): string {
  const L: string[] = [];
  L.push("");
  L.push(`◆ lacspace-inspect — site audit of ${site.seed}`);
  L.push(`  ${site.pageCount} page(s) · average ${site.averageGrade} (${site.averageScore}/100)`);
  L.push("");
  L.push("  Leaderboard");
  for (const e of site.leaderboard) {
    L.push(`    ${e.grade}  ${String(e.score).padStart(3)}  ${e.url}`);
  }
  if (site.commonIssues.length) {
    L.push("");
    L.push("  Most common issues");
    for (const i of site.commonIssues.slice(0, 8)) {
      L.push(`    ${ICON[i.status]} ×${i.count}  ${i.id} — ${i.message}`);
    }
  }
  if (site.duplicateTitles.length) {
    L.push("");
    L.push("  Duplicate <title> across pages");
    for (const d of site.duplicateTitles.slice(0, 5)) L.push(`    "${d.value}" — ${d.urls.length} pages`);
  }
  if (site.duplicateDescriptions.length) {
    L.push("");
    L.push("  Duplicate meta description across pages");
    for (const d of site.duplicateDescriptions.slice(0, 5)) L.push(`    "${d.value.slice(0, 60)}…" — ${d.urls.length} pages`);
  }
  if (site.brokenInternalLinks.length) {
    L.push("");
    L.push(`  Broken internal links (${site.brokenInternalLinks.length})`);
    for (const b of site.brokenInternalLinks.slice(0, 10)) L.push(`    ${b.status} ${b.to}  (on ${b.from})`);
  }
  L.push("");
  return L.join("\n");
}

/** Crawl-audit summary as Markdown (PR-comment ready). Pure. */
export function formatSiteMarkdown(site: SiteReport): string {
  const L: string[] = [];
  L.push(`## ◆ lacspace-inspect — site audit`);
  L.push("");
  L.push(`**Seed:** ${site.seed} · **${site.pageCount} pages** · average \`${site.averageGrade}\` (${site.averageScore}/100)`);
  L.push("");
  L.push("### Leaderboard");
  L.push("");
  L.push("| Grade | Score | URL |");
  L.push("| :---: | ---: | --- |");
  for (const e of site.leaderboard) L.push(`| \`${e.grade}\` | ${e.score} | ${e.url} |`);
  L.push("");
  if (site.commonIssues.length) {
    L.push("### Most common issues");
    L.push("");
    L.push("| Count | Check | Issue |");
    L.push("| ---: | --- | --- |");
    for (const i of site.commonIssues) L.push(`| ${i.count} | \`${i.id}\` | ${i.message} |`);
    L.push("");
  }
  if (site.duplicateTitles.length) {
    L.push("### Duplicate `<title>` across pages");
    L.push("");
    for (const d of site.duplicateTitles) L.push(`- **"${d.value}"** — ${d.urls.length} pages`);
    L.push("");
  }
  if (site.duplicateDescriptions.length) {
    L.push("### Duplicate meta descriptions");
    L.push("");
    for (const d of site.duplicateDescriptions) L.push(`- "${d.value.slice(0, 80)}…" — ${d.urls.length} pages`);
    L.push("");
  }
  if (site.brokenInternalLinks.length) {
    L.push(`### Broken internal links (${site.brokenInternalLinks.length})`);
    L.push("");
    for (const b of site.brokenInternalLinks) L.push(`- \`${b.status}\` ${b.to} — linked from ${b.from}`);
    L.push("");
  }
  return L.join("\n");
}

// ---------------- Batch leaderboard ----------------

/** A simple ranked table for `--input` batch runs. Pure. */
export function formatLeaderboard(entries: { url: string; score: number; grade: Grade }[]): string {
  const sorted = [...entries].sort((a, b) => b.score - a.score || a.url.localeCompare(b.url));
  const L: string[] = ["", "◆ lacspace-inspect — batch leaderboard", ""];
  sorted.forEach((e, i) => L.push(`  ${String(i + 1).padStart(2)}. ${e.grade}  ${String(e.score).padStart(3)}  ${e.url}`));
  L.push("");
  return L.join("\n");
}

// ---------------- Regressions ----------------

/** Render a baseline diff. Pure. */
export function formatRegressions(regs: Regression[]): string {
  if (regs.length === 0) return "  ✓ No regressions against the baseline.";
  const L: string[] = [`  ✗ ${regs.length} regression(s) against the baseline:`];
  for (const r of regs) L.push(`    - [${r.kind}] ${r.message}`);
  return L.join("\n");
}
