/**
 * React bindings for @lacspace/brand. React is an optional peer — import from
 * `@lacspace/brand/react` only if you use it.
 *
 * ```tsx
 * import { LacspaceMark } from "@lacspace/brand/react";
 * <LacspaceMark animation="craft" size={320} />
 * ```
 */

import * as React from "react";
import { mark, type MarkOptions } from "./mark.js";
import { animatedMark, type AnimateOptions, type AnimationName } from "./animate.js";

export interface LacspaceMarkProps extends Omit<MarkOptions, "style"> {
  /** Play an animation instead of a static mark. */
  animation?: AnimationName;
  /** Loop the animation (craft/pulse/float). */
  loop?: boolean;
  /** Static-mark render style: `filled` (default), `line` or `glyph`. */
  markStyle?: MarkOptions["style"];
  className?: string;
  style?: React.CSSProperties;
}

/**
 * The Lacspace mark — static, or animated when `animation` is set. Renders a
 * self-contained inline SVG (via `dangerouslySetInnerHTML`, but the SVG is fully
 * generated by this package, never user input).
 */
export function LacspaceMark({ animation, loop, className, style, markStyle, ...rest }: LacspaceMarkProps): React.ReactElement {
  const opts: MarkOptions = { ...rest, style: markStyle };
  const html = React.useMemo(() => {
    if (animation) {
      const a: AnimateOptions = { size: opts.size, background: opts.background, loop, uid: opts.uid };
      return animatedMark(animation, a);
    }
    return mark(opts);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [animation, loop, opts.size, opts.variant, markStyle, opts.background, opts.rounded, opts.network, opts.uid, opts.title]);

  return React.createElement("span", {
    className,
    style: { display: "inline-flex", lineHeight: 0, ...style },
    dangerouslySetInnerHTML: { __html: html },
  });
}

export default LacspaceMark;
