/**
 * ISO 3166-1 (all 249 officially assigned codes), with ITU E.164 calling codes,
 * ISO 4217 currencies, ccTLD and UN M49 continent. One row per country:
 * [alpha2, alpha3, numeric, name, calling codes, currencies, tld, region].
 * Verified in tests against ICU's region names, currency list and by
 * uniqueness/round-trip checks.
 */
export type Region = "Africa" | "Americas" | "Antarctica" | "Asia" | "Europe" | "Oceania";

export type Row = readonly [string, string, string, string, string, string, string, Region];

export const ROWS: readonly Row[] = [
  ["AD", "AND", "020", "Andorra", "376", "EUR", ".ad", "Europe"],
  ["AE", "ARE", "784", "United Arab Emirates", "971", "AED", ".ae", "Asia"],
  ["AF", "AFG", "004", "Afghanistan", "93", "AFN", ".af", "Asia"],
  ["AG", "ATG", "028", "Antigua and Barbuda", "1268", "XCD", ".ag", "Americas"],
  ["AI", "AIA", "660", "Anguilla", "1264", "XCD", ".ai", "Americas"],
  ["AL", "ALB", "008", "Albania", "355", "ALL", ".al", "Europe"],
  ["AM", "ARM", "051", "Armenia", "374", "AMD", ".am", "Asia"],
  ["AO", "AGO", "024", "Angola", "244", "AOA", ".ao", "Africa"],
  ["AQ", "ATA", "010", "Antarctica", "672", "", ".aq", "Antarctica"],
  ["AR", "ARG", "032", "Argentina", "54", "ARS", ".ar", "Americas"],
  ["AS", "ASM", "016", "American Samoa", "1684", "USD", ".as", "Oceania"],
  ["AT", "AUT", "040", "Austria", "43", "EUR", ".at", "Europe"],
  ["AU", "AUS", "036", "Australia", "61", "AUD", ".au", "Oceania"],
  ["AW", "ABW", "533", "Aruba", "297", "AWG", ".aw", "Americas"],
  ["AX", "ALA", "248", "Åland Islands", "358", "EUR", ".ax", "Europe"],
  ["AZ", "AZE", "031", "Azerbaijan", "994", "AZN", ".az", "Asia"],
  ["BA", "BIH", "070", "Bosnia and Herzegovina", "387", "BAM", ".ba", "Europe"],
  ["BB", "BRB", "052", "Barbados", "1246", "BBD", ".bb", "Americas"],
  ["BD", "BGD", "050", "Bangladesh", "880", "BDT", ".bd", "Asia"],
  ["BE", "BEL", "056", "Belgium", "32", "EUR", ".be", "Europe"],
  ["BF", "BFA", "854", "Burkina Faso", "226", "XOF", ".bf", "Africa"],
  ["BG", "BGR", "100", "Bulgaria", "359", "BGN", ".bg", "Europe"],
  ["BH", "BHR", "048", "Bahrain", "973", "BHD", ".bh", "Asia"],
  ["BI", "BDI", "108", "Burundi", "257", "BIF", ".bi", "Africa"],
  ["BJ", "BEN", "204", "Benin", "229", "XOF", ".bj", "Africa"],
  ["BL", "BLM", "652", "Saint Barthélemy", "590", "EUR", ".bl", "Americas"],
  ["BM", "BMU", "060", "Bermuda", "1441", "BMD", ".bm", "Americas"],
  ["BN", "BRN", "096", "Brunei Darussalam", "673", "BND", ".bn", "Asia"],
  ["BO", "BOL", "068", "Bolivia", "591", "BOB", ".bo", "Americas"],
  ["BQ", "BES", "535", "Bonaire, Sint Eustatius and Saba", "599", "USD", ".bq", "Americas"],
  ["BR", "BRA", "076", "Brazil", "55", "BRL", ".br", "Americas"],
  ["BS", "BHS", "044", "Bahamas", "1242", "BSD", ".bs", "Americas"],
  ["BT", "BTN", "064", "Bhutan", "975", "BTN,INR", ".bt", "Asia"],
  ["BV", "BVT", "074", "Bouvet Island", "47", "NOK", ".bv", "Antarctica"],
  ["BW", "BWA", "072", "Botswana", "267", "BWP", ".bw", "Africa"],
  ["BY", "BLR", "112", "Belarus", "375", "BYN", ".by", "Europe"],
  ["BZ", "BLZ", "084", "Belize", "501", "BZD", ".bz", "Americas"],
  ["CA", "CAN", "124", "Canada", "1", "CAD", ".ca", "Americas"],
  ["CC", "CCK", "166", "Cocos (Keeling) Islands", "61", "AUD", ".cc", "Oceania"],
  ["CD", "COD", "180", "Congo, Democratic Republic of the", "243", "CDF", ".cd", "Africa"],
  ["CF", "CAF", "140", "Central African Republic", "236", "XAF", ".cf", "Africa"],
  ["CG", "COG", "178", "Congo", "242", "XAF", ".cg", "Africa"],
  ["CH", "CHE", "756", "Switzerland", "41", "CHF", ".ch", "Europe"],
  ["CI", "CIV", "384", "Côte d'Ivoire", "225", "XOF", ".ci", "Africa"],
  ["CK", "COK", "184", "Cook Islands", "682", "NZD", ".ck", "Oceania"],
  ["CL", "CHL", "152", "Chile", "56", "CLP", ".cl", "Americas"],
  ["CM", "CMR", "120", "Cameroon", "237", "XAF", ".cm", "Africa"],
  ["CN", "CHN", "156", "China", "86", "CNY", ".cn", "Asia"],
  ["CO", "COL", "170", "Colombia", "57", "COP", ".co", "Americas"],
  ["CR", "CRI", "188", "Costa Rica", "506", "CRC", ".cr", "Americas"],
  ["CU", "CUB", "192", "Cuba", "53", "CUP", ".cu", "Americas"],
  ["CV", "CPV", "132", "Cabo Verde", "238", "CVE", ".cv", "Africa"],
  ["CW", "CUW", "531", "Curaçao", "599", "XCG", ".cw", "Americas"],
  ["CX", "CXR", "162", "Christmas Island", "61", "AUD", ".cx", "Oceania"],
  ["CY", "CYP", "196", "Cyprus", "357", "EUR", ".cy", "Asia"],
  ["CZ", "CZE", "203", "Czechia", "420", "CZK", ".cz", "Europe"],
  ["DE", "DEU", "276", "Germany", "49", "EUR", ".de", "Europe"],
  ["DJ", "DJI", "262", "Djibouti", "253", "DJF", ".dj", "Africa"],
  ["DK", "DNK", "208", "Denmark", "45", "DKK", ".dk", "Europe"],
  ["DM", "DMA", "212", "Dominica", "1767", "XCD", ".dm", "Americas"],
  ["DO", "DOM", "214", "Dominican Republic", "1809,1829,1849", "DOP", ".do", "Americas"],
  ["DZ", "DZA", "012", "Algeria", "213", "DZD", ".dz", "Africa"],
  ["EC", "ECU", "218", "Ecuador", "593", "USD", ".ec", "Americas"],
  ["EE", "EST", "233", "Estonia", "372", "EUR", ".ee", "Europe"],
  ["EG", "EGY", "818", "Egypt", "20", "EGP", ".eg", "Africa"],
  ["EH", "ESH", "732", "Western Sahara", "212", "MAD", ".eh", "Africa"],
  ["ER", "ERI", "232", "Eritrea", "291", "ERN", ".er", "Africa"],
  ["ES", "ESP", "724", "Spain", "34", "EUR", ".es", "Europe"],
  ["ET", "ETH", "231", "Ethiopia", "251", "ETB", ".et", "Africa"],
  ["FI", "FIN", "246", "Finland", "358", "EUR", ".fi", "Europe"],
  ["FJ", "FJI", "242", "Fiji", "679", "FJD", ".fj", "Oceania"],
  ["FK", "FLK", "238", "Falkland Islands (Malvinas)", "500", "FKP", ".fk", "Americas"],
  ["FM", "FSM", "583", "Micronesia, Federated States of", "691", "USD", ".fm", "Oceania"],
  ["FO", "FRO", "234", "Faroe Islands", "298", "DKK", ".fo", "Europe"],
  ["FR", "FRA", "250", "France", "33", "EUR", ".fr", "Europe"],
  ["GA", "GAB", "266", "Gabon", "241", "XAF", ".ga", "Africa"],
  ["GB", "GBR", "826", "United Kingdom", "44", "GBP", ".uk", "Europe"],
  ["GD", "GRD", "308", "Grenada", "1473", "XCD", ".gd", "Americas"],
  ["GE", "GEO", "268", "Georgia", "995", "GEL", ".ge", "Asia"],
  ["GF", "GUF", "254", "French Guiana", "594", "EUR", ".gf", "Americas"],
  ["GG", "GGY", "831", "Guernsey", "44", "GBP", ".gg", "Europe"],
  ["GH", "GHA", "288", "Ghana", "233", "GHS", ".gh", "Africa"],
  ["GI", "GIB", "292", "Gibraltar", "350", "GIP", ".gi", "Europe"],
  ["GL", "GRL", "304", "Greenland", "299", "DKK", ".gl", "Americas"],
  ["GM", "GMB", "270", "Gambia", "220", "GMD", ".gm", "Africa"],
  ["GN", "GIN", "324", "Guinea", "224", "GNF", ".gn", "Africa"],
  ["GP", "GLP", "312", "Guadeloupe", "590", "EUR", ".gp", "Americas"],
  ["GQ", "GNQ", "226", "Equatorial Guinea", "240", "XAF", ".gq", "Africa"],
  ["GR", "GRC", "300", "Greece", "30", "EUR", ".gr", "Europe"],
  ["GS", "SGS", "239", "South Georgia and the South Sandwich Islands", "500", "GBP", ".gs", "Antarctica"],
  ["GT", "GTM", "320", "Guatemala", "502", "GTQ", ".gt", "Americas"],
  ["GU", "GUM", "316", "Guam", "1671", "USD", ".gu", "Oceania"],
  ["GW", "GNB", "624", "Guinea-Bissau", "245", "XOF", ".gw", "Africa"],
  ["GY", "GUY", "328", "Guyana", "592", "GYD", ".gy", "Americas"],
  ["HK", "HKG", "344", "Hong Kong", "852", "HKD", ".hk", "Asia"],
  ["HM", "HMD", "334", "Heard Island and McDonald Islands", "672", "AUD", ".hm", "Antarctica"],
  ["HN", "HND", "340", "Honduras", "504", "HNL", ".hn", "Americas"],
  ["HR", "HRV", "191", "Croatia", "385", "EUR", ".hr", "Europe"],
  ["HT", "HTI", "332", "Haiti", "509", "HTG,USD", ".ht", "Americas"],
  ["HU", "HUN", "348", "Hungary", "36", "HUF", ".hu", "Europe"],
  ["ID", "IDN", "360", "Indonesia", "62", "IDR", ".id", "Asia"],
  ["IE", "IRL", "372", "Ireland", "353", "EUR", ".ie", "Europe"],
  ["IL", "ISR", "376", "Israel", "972", "ILS", ".il", "Asia"],
  ["IM", "IMN", "833", "Isle of Man", "44", "GBP", ".im", "Europe"],
  ["IN", "IND", "356", "India", "91", "INR", ".in", "Asia"],
  ["IO", "IOT", "086", "British Indian Ocean Territory", "246", "USD", ".io", "Asia"],
  ["IQ", "IRQ", "368", "Iraq", "964", "IQD", ".iq", "Asia"],
  ["IR", "IRN", "364", "Iran", "98", "IRR", ".ir", "Asia"],
  ["IS", "ISL", "352", "Iceland", "354", "ISK", ".is", "Europe"],
  ["IT", "ITA", "380", "Italy", "39", "EUR", ".it", "Europe"],
  ["JE", "JEY", "832", "Jersey", "44", "GBP", ".je", "Europe"],
  ["JM", "JAM", "388", "Jamaica", "1876,1658", "JMD", ".jm", "Americas"],
  ["JO", "JOR", "400", "Jordan", "962", "JOD", ".jo", "Asia"],
  ["JP", "JPN", "392", "Japan", "81", "JPY", ".jp", "Asia"],
  ["KE", "KEN", "404", "Kenya", "254", "KES", ".ke", "Africa"],
  ["KG", "KGZ", "417", "Kyrgyzstan", "996", "KGS", ".kg", "Asia"],
  ["KH", "KHM", "116", "Cambodia", "855", "KHR", ".kh", "Asia"],
  ["KI", "KIR", "296", "Kiribati", "686", "AUD", ".ki", "Oceania"],
  ["KM", "COM", "174", "Comoros", "269", "KMF", ".km", "Africa"],
  ["KN", "KNA", "659", "Saint Kitts and Nevis", "1869", "XCD", ".kn", "Americas"],
  ["KP", "PRK", "408", "Korea, Democratic People's Republic of", "850", "KPW", ".kp", "Asia"],
  ["KR", "KOR", "410", "Korea, Republic of", "82", "KRW", ".kr", "Asia"],
  ["KW", "KWT", "414", "Kuwait", "965", "KWD", ".kw", "Asia"],
  ["KY", "CYM", "136", "Cayman Islands", "1345", "KYD", ".ky", "Americas"],
  ["KZ", "KAZ", "398", "Kazakhstan", "7", "KZT", ".kz", "Asia"],
  ["LA", "LAO", "418", "Lao People's Democratic Republic", "856", "LAK", ".la", "Asia"],
  ["LB", "LBN", "422", "Lebanon", "961", "LBP", ".lb", "Asia"],
  ["LC", "LCA", "662", "Saint Lucia", "1758", "XCD", ".lc", "Americas"],
  ["LI", "LIE", "438", "Liechtenstein", "423", "CHF", ".li", "Europe"],
  ["LK", "LKA", "144", "Sri Lanka", "94", "LKR", ".lk", "Asia"],
  ["LR", "LBR", "430", "Liberia", "231", "LRD", ".lr", "Africa"],
  ["LS", "LSO", "426", "Lesotho", "266", "LSL,ZAR", ".ls", "Africa"],
  ["LT", "LTU", "440", "Lithuania", "370", "EUR", ".lt", "Europe"],
  ["LU", "LUX", "442", "Luxembourg", "352", "EUR", ".lu", "Europe"],
  ["LV", "LVA", "428", "Latvia", "371", "EUR", ".lv", "Europe"],
  ["LY", "LBY", "434", "Libya", "218", "LYD", ".ly", "Africa"],
  ["MA", "MAR", "504", "Morocco", "212", "MAD", ".ma", "Africa"],
  ["MC", "MCO", "492", "Monaco", "377", "EUR", ".mc", "Europe"],
  ["MD", "MDA", "498", "Moldova", "373", "MDL", ".md", "Europe"],
  ["ME", "MNE", "499", "Montenegro", "382", "EUR", ".me", "Europe"],
  ["MF", "MAF", "663", "Saint Martin (French part)", "590", "EUR", ".mf", "Americas"],
  ["MG", "MDG", "450", "Madagascar", "261", "MGA", ".mg", "Africa"],
  ["MH", "MHL", "584", "Marshall Islands", "692", "USD", ".mh", "Oceania"],
  ["MK", "MKD", "807", "North Macedonia", "389", "MKD", ".mk", "Europe"],
  ["ML", "MLI", "466", "Mali", "223", "XOF", ".ml", "Africa"],
  ["MM", "MMR", "104", "Myanmar", "95", "MMK", ".mm", "Asia"],
  ["MN", "MNG", "496", "Mongolia", "976", "MNT", ".mn", "Asia"],
  ["MO", "MAC", "446", "Macao", "853", "MOP", ".mo", "Asia"],
  ["MP", "MNP", "580", "Northern Mariana Islands", "1670", "USD", ".mp", "Oceania"],
  ["MQ", "MTQ", "474", "Martinique", "596", "EUR", ".mq", "Americas"],
  ["MR", "MRT", "478", "Mauritania", "222", "MRU", ".mr", "Africa"],
  ["MS", "MSR", "500", "Montserrat", "1664", "XCD", ".ms", "Americas"],
  ["MT", "MLT", "470", "Malta", "356", "EUR", ".mt", "Europe"],
  ["MU", "MUS", "480", "Mauritius", "230", "MUR", ".mu", "Africa"],
  ["MV", "MDV", "462", "Maldives", "960", "MVR", ".mv", "Asia"],
  ["MW", "MWI", "454", "Malawi", "265", "MWK", ".mw", "Africa"],
  ["MX", "MEX", "484", "Mexico", "52", "MXN", ".mx", "Americas"],
  ["MY", "MYS", "458", "Malaysia", "60", "MYR", ".my", "Asia"],
  ["MZ", "MOZ", "508", "Mozambique", "258", "MZN", ".mz", "Africa"],
  ["NA", "NAM", "516", "Namibia", "264", "NAD,ZAR", ".na", "Africa"],
  ["NC", "NCL", "540", "New Caledonia", "687", "XPF", ".nc", "Oceania"],
  ["NE", "NER", "562", "Niger", "227", "XOF", ".ne", "Africa"],
  ["NF", "NFK", "574", "Norfolk Island", "672", "AUD", ".nf", "Oceania"],
  ["NG", "NGA", "566", "Nigeria", "234", "NGN", ".ng", "Africa"],
  ["NI", "NIC", "558", "Nicaragua", "505", "NIO", ".ni", "Americas"],
  ["NL", "NLD", "528", "Netherlands", "31", "EUR", ".nl", "Europe"],
  ["NO", "NOR", "578", "Norway", "47", "NOK", ".no", "Europe"],
  ["NP", "NPL", "524", "Nepal", "977", "NPR", ".np", "Asia"],
  ["NR", "NRU", "520", "Nauru", "674", "AUD", ".nr", "Oceania"],
  ["NU", "NIU", "570", "Niue", "683", "NZD", ".nu", "Oceania"],
  ["NZ", "NZL", "554", "New Zealand", "64", "NZD", ".nz", "Oceania"],
  ["OM", "OMN", "512", "Oman", "968", "OMR", ".om", "Asia"],
  ["PA", "PAN", "591", "Panama", "507", "PAB,USD", ".pa", "Americas"],
  ["PE", "PER", "604", "Peru", "51", "PEN", ".pe", "Americas"],
  ["PF", "PYF", "258", "French Polynesia", "689", "XPF", ".pf", "Oceania"],
  ["PG", "PNG", "598", "Papua New Guinea", "675", "PGK", ".pg", "Oceania"],
  ["PH", "PHL", "608", "Philippines", "63", "PHP", ".ph", "Asia"],
  ["PK", "PAK", "586", "Pakistan", "92", "PKR", ".pk", "Asia"],
  ["PL", "POL", "616", "Poland", "48", "PLN", ".pl", "Europe"],
  ["PM", "SPM", "666", "Saint Pierre and Miquelon", "508", "EUR", ".pm", "Americas"],
  ["PN", "PCN", "612", "Pitcairn", "64", "NZD", ".pn", "Oceania"],
  ["PR", "PRI", "630", "Puerto Rico", "1787,1939", "USD", ".pr", "Americas"],
  ["PS", "PSE", "275", "Palestine, State of", "970", "ILS,JOD", ".ps", "Asia"],
  ["PT", "PRT", "620", "Portugal", "351", "EUR", ".pt", "Europe"],
  ["PW", "PLW", "585", "Palau", "680", "USD", ".pw", "Oceania"],
  ["PY", "PRY", "600", "Paraguay", "595", "PYG", ".py", "Americas"],
  ["QA", "QAT", "634", "Qatar", "974", "QAR", ".qa", "Asia"],
  ["RE", "REU", "638", "Réunion", "262", "EUR", ".re", "Africa"],
  ["RO", "ROU", "642", "Romania", "40", "RON", ".ro", "Europe"],
  ["RS", "SRB", "688", "Serbia", "381", "RSD", ".rs", "Europe"],
  ["RU", "RUS", "643", "Russian Federation", "7", "RUB", ".ru", "Europe"],
  ["RW", "RWA", "646", "Rwanda", "250", "RWF", ".rw", "Africa"],
  ["SA", "SAU", "682", "Saudi Arabia", "966", "SAR", ".sa", "Asia"],
  ["SB", "SLB", "090", "Solomon Islands", "677", "SBD", ".sb", "Oceania"],
  ["SC", "SYC", "690", "Seychelles", "248", "SCR", ".sc", "Africa"],
  ["SD", "SDN", "729", "Sudan", "249", "SDG", ".sd", "Africa"],
  ["SE", "SWE", "752", "Sweden", "46", "SEK", ".se", "Europe"],
  ["SG", "SGP", "702", "Singapore", "65", "SGD", ".sg", "Asia"],
  ["SH", "SHN", "654", "Saint Helena, Ascension and Tristan da Cunha", "290,247", "SHP", ".sh", "Africa"],
  ["SI", "SVN", "705", "Slovenia", "386", "EUR", ".si", "Europe"],
  ["SJ", "SJM", "744", "Svalbard and Jan Mayen", "47", "NOK", ".sj", "Europe"],
  ["SK", "SVK", "703", "Slovakia", "421", "EUR", ".sk", "Europe"],
  ["SL", "SLE", "694", "Sierra Leone", "232", "SLE", ".sl", "Africa"],
  ["SM", "SMR", "674", "San Marino", "378", "EUR", ".sm", "Europe"],
  ["SN", "SEN", "686", "Senegal", "221", "XOF", ".sn", "Africa"],
  ["SO", "SOM", "706", "Somalia", "252", "SOS", ".so", "Africa"],
  ["SR", "SUR", "740", "Suriname", "597", "SRD", ".sr", "Americas"],
  ["SS", "SSD", "728", "South Sudan", "211", "SSP", ".ss", "Africa"],
  ["ST", "STP", "678", "Sao Tome and Principe", "239", "STN", ".st", "Africa"],
  ["SV", "SLV", "222", "El Salvador", "503", "USD", ".sv", "Americas"],
  ["SX", "SXM", "534", "Sint Maarten (Dutch part)", "1721", "XCG", ".sx", "Americas"],
  ["SY", "SYR", "760", "Syrian Arab Republic", "963", "SYP", ".sy", "Asia"],
  ["SZ", "SWZ", "748", "Eswatini", "268", "SZL,ZAR", ".sz", "Africa"],
  ["TC", "TCA", "796", "Turks and Caicos Islands", "1649", "USD", ".tc", "Americas"],
  ["TD", "TCD", "148", "Chad", "235", "XAF", ".td", "Africa"],
  ["TF", "ATF", "260", "French Southern Territories", "262", "EUR", ".tf", "Antarctica"],
  ["TG", "TGO", "768", "Togo", "228", "XOF", ".tg", "Africa"],
  ["TH", "THA", "764", "Thailand", "66", "THB", ".th", "Asia"],
  ["TJ", "TJK", "762", "Tajikistan", "992", "TJS", ".tj", "Asia"],
  ["TK", "TKL", "772", "Tokelau", "690", "NZD", ".tk", "Oceania"],
  ["TL", "TLS", "626", "Timor-Leste", "670", "USD", ".tl", "Asia"],
  ["TM", "TKM", "795", "Turkmenistan", "993", "TMT", ".tm", "Asia"],
  ["TN", "TUN", "788", "Tunisia", "216", "TND", ".tn", "Africa"],
  ["TO", "TON", "776", "Tonga", "676", "TOP", ".to", "Oceania"],
  ["TR", "TUR", "792", "Türkiye", "90", "TRY", ".tr", "Asia"],
  ["TT", "TTO", "780", "Trinidad and Tobago", "1868", "TTD", ".tt", "Americas"],
  ["TV", "TUV", "798", "Tuvalu", "688", "AUD", ".tv", "Oceania"],
  ["TW", "TWN", "158", "Taiwan", "886", "TWD", ".tw", "Asia"],
  ["TZ", "TZA", "834", "Tanzania, United Republic of", "255", "TZS", ".tz", "Africa"],
  ["UA", "UKR", "804", "Ukraine", "380", "UAH", ".ua", "Europe"],
  ["UG", "UGA", "800", "Uganda", "256", "UGX", ".ug", "Africa"],
  ["UM", "UMI", "581", "United States Minor Outlying Islands", "1", "USD", ".um", "Oceania"],
  ["US", "USA", "840", "United States of America", "1", "USD", ".us", "Americas"],
  ["UY", "URY", "858", "Uruguay", "598", "UYU", ".uy", "Americas"],
  ["UZ", "UZB", "860", "Uzbekistan", "998", "UZS", ".uz", "Asia"],
  ["VA", "VAT", "336", "Holy See", "39", "EUR", ".va", "Europe"],
  ["VC", "VCT", "670", "Saint Vincent and the Grenadines", "1784", "XCD", ".vc", "Americas"],
  ["VE", "VEN", "862", "Venezuela", "58", "VES", ".ve", "Americas"],
  ["VG", "VGB", "092", "Virgin Islands (British)", "1284", "USD", ".vg", "Americas"],
  ["VI", "VIR", "850", "Virgin Islands (U.S.)", "1340", "USD", ".vi", "Americas"],
  ["VN", "VNM", "704", "Viet Nam", "84", "VND", ".vn", "Asia"],
  ["VU", "VUT", "548", "Vanuatu", "678", "VUV", ".vu", "Oceania"],
  ["WF", "WLF", "876", "Wallis and Futuna", "681", "XPF", ".wf", "Oceania"],
  ["WS", "WSM", "882", "Samoa", "685", "WST", ".ws", "Oceania"],
  ["YE", "YEM", "887", "Yemen", "967", "YER", ".ye", "Asia"],
  ["YT", "MYT", "175", "Mayotte", "262", "EUR", ".yt", "Africa"],
  ["ZA", "ZAF", "710", "South Africa", "27", "ZAR", ".za", "Africa"],
  ["ZM", "ZMB", "894", "Zambia", "260", "ZMW", ".zm", "Africa"],
  ["ZW", "ZWE", "716", "Zimbabwe", "263", "ZWG", ".zw", "Africa"],
];

/** Everyday names that differ from the ISO short name, for lookups. */
export const ALIASES: Record<string, string> = {
  "usa": "US", "united states": "US", "america": "US", "u.s.": "US", "u.s.a.": "US",
  "uk": "GB", "britain": "GB", "great britain": "GB", "england": "GB", "scotland": "GB", "wales": "GB",
  "russia": "RU", "south korea": "KR", "korea": "KR", "north korea": "KP", "vietnam": "VN", "laos": "LA",
  "iran": "IR", "syria": "SY", "tanzania": "TZ", "bolivia": "BO", "venezuela": "VE", "moldova": "MD",
  "czech republic": "CZ", "turkey": "TR", "macedonia": "MK", "swaziland": "SZ", "burma": "MM",
  "ivory coast": "CI", "cape verde": "CV", "east timor": "TL", "micronesia": "FM", "palestine": "PS",
  "vatican": "VA", "vatican city": "VA", "drc": "CD", "dr congo": "CD", "congo-kinshasa": "CD", "congo-brazzaville": "CG",
  "uae": "AE", "emirates": "AE", "hong kong sar": "HK", "macau": "MO", "brunei": "BN", "falklands": "FK",
  "the netherlands": "NL", "holland": "NL", "the bahamas": "BS", "the gambia": "GM", "taiwan, province of china": "TW",
  "são tomé and príncipe": "ST", "st. lucia": "LC", "st lucia": "LC", "st. kitts": "KN", "st. vincent": "VC",
  "reunion": "RE", "curacao": "CW", "aland": "AX", "aland islands": "AX", "cote d'ivoire": "CI", "turkiye": "TR",
  "caribbean netherlands": "BQ", "palestinian territories": "PS", "pitcairn islands": "PN",
  "u.s. outlying islands": "UM", "us outlying islands": "UM", "british virgin islands": "VG", "bvi": "VG",
  "u.s. virgin islands": "VI", "us virgin islands": "VI", "south georgia": "GS", "saint helena": "SH",
  "saint martin": "MF", "sint maarten": "SX", "heard and mcdonald islands": "HM", "saint vincent and grenadines": "VC",
  "bosnia": "BA", "trinidad": "TT", "tobago": "TT",
};
