import { decodeBytes, htmlTitle, htmlToText, sniffCharset } from "./html";
import { fnv1a64, matchExpect, normalise } from "./normalise";
import { isPdf, pdfInfo, pdfText, type PdfInfo } from "./pdf";
import type { CheckOptions, Kind, PdfQuality, Summary, TlsKind, WatchError, WatchItem, WatchResult } from "./types";

/** Default User-Agent: a current desktop Chrome (some government sites block unknown agents). */
export const DEFAULT_USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36";

const DEFAULTS = {
  timeoutMs: 15000,
  maxBytes: 10 * 1024 * 1024,
  concurrency: 4,
  retries: 1,
  retryDelayMs: 500,
  minTextChars: 200,
};

// ---------------------------------------------------------------- errors

const TLS_CHAIN = new Set(["UNABLE_TO_VERIFY_LEAF_SIGNATURE", "UNABLE_TO_GET_ISSUER_CERT", "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"]);
const TLS_EXPIRED = new Set(["CERT_HAS_EXPIRED", "CERT_NOT_YET_VALID"]);
const TLS_SELF = new Set(["DEPTH_ZERO_SELF_SIGNED_CERT", "SELF_SIGNED_CERT_IN_CHAIN"]);
const TLS_HOST = new Set(["ERR_TLS_CERT_ALTNAME_INVALID"]);
const TLS_RE = /^(CERT_|UNABLE_TO_VERIFY_LEAF_SIGNATURE|UNABLE_TO_GET_ISSUER_CERT|ERR_TLS_|ERR_SSL_|SELF_SIGNED_|DEPTH_ZERO_|UNABLE_TO_DECRYPT_CERT|UNABLE_TO_DECODE_ISSUER|INVALID_CA|PATH_LENGTH_EXCEEDED|INVALID_PURPOSE|CERT_UNTRUSTED|CERT_REJECTED|HOSTNAME_MISMATCH)/;
const DNS = new Set(["ENOTFOUND", "EAI_AGAIN", "EAI_NONAME", "EAI_NODATA", "EAI_FAIL"]);
const TIMEOUTS = new Set(["ETIMEDOUT", "UND_ERR_CONNECT_TIMEOUT", "UND_ERR_HEADERS_TIMEOUT", "UND_ERR_BODY_TIMEOUT", "ABORT_ERR"]);

/** The sub-class of a TLS error code. */
export function tlsKindOf(code: string): TlsKind {
  if (TLS_CHAIN.has(code)) return "chain";
  if (TLS_EXPIRED.has(code)) return "expired";
  if (TLS_SELF.has(code)) return "self_signed";
  if (TLS_HOST.has(code)) return "hostname";
  return "other";
}

function findCode(err: unknown): string | undefined {
  let e: any = err;
  for (let i = 0; i < 6 && e; i++) {
    if (typeof e.code === "string" && e.code !== "ERR_INVALID_STATE") return e.code;
    if (Array.isArray(e.errors) && e.errors[0]) {
      const c = findCode(e.errors[0]);
      if (c) return c;
    }
    e = e.cause;
  }
  return undefined;
}

/** Classify a thrown fetch error. */
export function classifyError(err: unknown): { error: WatchError; tlsKind?: TlsKind; detail: string } {
  const e: any = err;
  const name: string = e?.name ?? "";
  const msg: string = String(e?.cause?.message ?? e?.message ?? e ?? "");
  const code = findCode(err);
  if (name === "AbortError" || name === "TimeoutError" || e?.cause?.name === "AbortError" || e?.cause?.name === "TimeoutError")
    return { error: "timeout", detail: code ?? name };
  if (code) {
    if (TLS_RE.test(code)) return { error: "tls", tlsKind: tlsKindOf(code), detail: code };
    if (DNS.has(code)) return { error: "dns", detail: code };
    if (TIMEOUTS.has(code)) return { error: "timeout", detail: code };
    if (code === "EPROTO" && /ssl|tls/i.test(msg)) return { error: "tls", tlsKind: "other", detail: `${code}: ${msg}`.slice(0, 200) };
    return { error: "network", detail: code };
  }
  if (/certificate|ssl|tls/i.test(msg)) return { error: "tls", tlsKind: "other", detail: msg.slice(0, 200) };
  if (/getaddrinfo|ENOTFOUND|name not resolved/i.test(msg)) return { error: "dns", detail: msg.slice(0, 200) };
  return { error: "network", detail: msg.slice(0, 200) || "fetch failed" };
}

// ---------------------------------------------------------------- placeholder

const PLACEHOLDER_PATTERNS: RegExp[] = [
  /^\s*this is (a )?test\b/i,
  /^\s*test( page)?\s*$/i,
  /\bcoming soon\b/i,
  /\bunder construction\b/i,
  /^\s*it works!?/i,
  /\bwelcome to nginx\b/i,
  /\bapache2? (ubuntu |debian )?default page\b/i,
  /\btest page for the (apache|nginx)/i,
  /^\s*index of \//i,
  /\bdefault web site page\b/i,
  /\bweb server'?s default page\b/i,
  /\bthis page is (auto)?generated by plesk\b/i,
  /\bthere is no web ?site configured at this address\b/i,
  /\bfuture home of something quite cool\b/i,
  /\bcpanel\b.{0,80}\b(default|account (has been )?suspended)/i,
  /\b(site|website) is (currently )?(under|down for) maintenance\b/i,
  /\baccount (has been )?suspended\b/i,
  /\bthis (domain|site) (has expired|is parked|is for sale)\b/i,
  /^\s*iis windows server\b/i,
];

/** Why a page looks like a placeholder, or null. `title` is checked alongside the visible text. */
export function placeholderReason(text: string, bytes: number, title = "", minTextChars = DEFAULTS.minTextChars): string | null {
  const t = normalise(text);
  const short = t.length < 3000;
  if (short) {
    for (const re of PLACEHOLDER_PATTERNS) {
      if (re.test(t.slice(0, 400)) || (title && re.test(normalise(title)))) return `matches ${re.source}`;
    }
  }
  if (bytes < minTextChars || t.length < minTextChars) return `only ${t.length} chars of visible text`;
  return null;
}

/**
 * Is this a placeholder page? Visible text shorter than 200 chars (or a body under 200 bytes),
 * or a short page reading like a test page, default server page, "coming soon", maintenance or suspended account.
 */
export function isPlaceholder(text: string, bytes: number = text.length): boolean {
  return placeholderReason(text, bytes) !== null;
}

// ---------------------------------------------------------------- JS app shells

const APP_MARKERS: [RegExp, string][] = [
  [/<div\b[^>]*\bid\s*=\s*["']?(?:app|root|__next|__nuxt|q-app|svelte|main-app|react-root|ember-app)\b["']?[^>]*>\s*<\/div>/i, "empty app mount point"],
  [/<div\b[^>]*\bid\s*=\s*["']?[\w-]+["']?[^>]*>\s*<\/div>\s*(?:<link\b[^>]*>\s*)*<script\b[^>]*\btype\s*=\s*["']?module/i, "empty mount point before a module script"],
  [/<noscript\b[^>]*>[^<]{0,300}?\b(?:enable|turn on|activate)\s+javascript/i, "<noscript> asks to enable JavaScript"],
  [/<noscript\b[^>]*>[^<]{0,300}?\bjavascript\s+(?:is\s+)?(?:required|disabled|must be enabled)/i, "<noscript> says JavaScript is required"],
  [/\b__NEXT_DATA__\b|\/_next\/static\//, "Next.js bundle"],
  [/\bwindow\.__NUXT__|\/_nuxt\//, "Nuxt bundle"],
  [/<script\b[^>]*\btype\s*=\s*["']?module["']?[^>]*\bsrc\s*=/i, "module script bundle"],
  [/\/(?:assets|build|static\/js|js|dist)\/(?:index|app|main|bundle|vendor|runtime|chunk)[.-][\w.-]*\.js\b/i, "hashed JS bundle"],
  [/\bchunk-vendors\b|\bapp\.[0-9a-f]{6,}\.js\b|\bmain\.[0-9a-f]{6,}\.js\b/i, "webpack bundle"],
  [/\bng-app\b|\bng-version\s*=|<app-root\b/i, "Angular app"],
  [/\bdata-reactroot\b|\bdata-server-rendered\b/i, "React/Vue root"],
];

/**
 * Why an HTML page looks like a JavaScript app shell (content rendered client-side), or null.
 * Needs both: less visible text than `minTextChars`, and a marker in the raw HTML such as an empty
 * `<div id="app|root">`, `<noscript>…enable JavaScript…`, `__NEXT_DATA__`, module/hashed bundles, `ng-app`.
 * @since 1.2.0
 */
export function jsAppReason(rawHtml: string, text: string, minTextChars = DEFAULTS.minTextChars): string | null {
  if (normalise(text).length >= minTextChars) return null;
  const hits: string[] = [];
  for (const [re, label] of APP_MARKERS) if (re.test(rawHtml) && !hits.includes(label)) hits.push(label);
  return hits.length ? hits.slice(0, 3).join(", ") : null;
}

// ---------------------------------------------------------------- bot protection

const CHALLENGE_BODY: [RegExp, string][] = [
  [/<title>\s*just a moment\.{0,3}\s*<\/title>/i, "Cloudflare challenge"],
  [/attention required!?\s*\|\s*cloudflare/i, "Cloudflare block page"],
  [/\bcf[-_]chl[-_]|\/cdn-cgi\/challenge-platform\/|\bchallenge-platform\b|\bcf-browser-verification\b/i, "Cloudflare challenge"],
  [/sucuri website firewall|\bsucuri\b[\s\S]{0,200}access denied/i, "Sucuri firewall"],
  [/incapsula incident id|_incapsula_resource|\bimperva\b/i, "Imperva/Incapsula"],
  [/access denied[\s\S]{0,600}reference\s*#\s*[0-9a-f]+\.[0-9a-f.]+/i, "Akamai"],
  [/captcha-delivery\.com|\bdatadome\b/i, "DataDome"],
  [/\bddos-guard\b/i, "DDoS-Guard"],
];

/**
 * Why a 403/429/503 response looks like a bot-protection challenge, or null. Looks at the
 * `cf-mitigated` header, and at a `server: cloudflare` (or other WAF) response whose body is a
 * challenge page ("Just a moment…", "Attention Required", `cf-chl`, `challenge-platform`), or a
 * Sucuri / Imperva / Akamai ("Access Denied … Reference #") / DataDome block page. @since 1.2.0
 */
export function botBlockReason(status: number, headers: Headers | Record<string, string> | null | undefined, body = ""): string | null {
  if (status !== 403 && status !== 429 && status !== 503) return null;
  const h = (k: string): string | null => {
    if (!headers) return null;
    if (typeof (headers as Headers).get === "function") return (headers as Headers).get(k);
    const rec = headers as Record<string, string>;
    for (const key of Object.keys(rec)) if (key.toLowerCase() === k) return rec[key]!;
    return null;
  };
  const mitigated = h("cf-mitigated");
  if (mitigated) return `Cloudflare ${mitigated} (cf-mitigated)`;
  const server = (h("server") ?? "").toLowerCase();
  for (const [re, label] of CHALLENGE_BODY) if (re.test(body)) return `${label} (HTTP ${status}${server ? `, server: ${server}` : ""})`;
  if (h("x-sucuri-id") || /sucuri|cloudproxy/.test(server)) return `Sucuri firewall (HTTP ${status})`;
  if (h("x-iinfo") || /incapsula/i.test(h("x-cdn") ?? "")) return `Imperva/Incapsula (HTTP ${status})`;
  if (h("x-datadome") || h("x-dd-b")) return `DataDome (HTTP ${status})`;
  return null;
}

// ---------------------------------------------------------------- extraction

function detectKind(declared: WatchItem["kind"], contentType: string | null, bytes: Uint8Array, url: string): Kind {
  if (declared && declared !== "auto") return declared;
  const ct = (contentType ?? "").toLowerCase();
  if (ct.includes("application/pdf") || ct.includes("application/x-pdf")) return "pdf";
  if (ct.includes("html") || ct.includes("xml")) return isPdf(bytes) ? "pdf" : "html";
  if (ct.startsWith("text/plain")) return "text";
  if (isPdf(bytes)) return "pdf";
  let path = url;
  try {
    path = new URL(url).pathname;
  } catch {
    /* relative or odd */
  }
  if (/\.pdf$/i.test(path)) return "pdf";
  if (/\.(txt|csv)$/i.test(path)) return "text";
  return "html";
}

/**
 * Extract visible text. `html`: tags/scripts dropped, entities decoded, charset sniffed.
 * `text`: decoded as-is. `pdf`: {@link pdfText}. Strings are taken as already-decoded.
 */
export async function extractText(input: Uint8Array | string, kind: Kind, contentType?: string | null): Promise<string> {
  if (kind === "pdf") {
    const bytes = typeof input === "string" ? Uint8Array.from(input, (c) => c.charCodeAt(0) & 255) : input;
    return pdfText(bytes);
  }
  const raw = typeof input === "string" ? input : decodeBytes(input, sniffCharset(input, contentType));
  return kind === "html" ? htmlToText(raw) : raw;
}

// ---------------------------------------------------------------- fetch

interface Fetched {
  status: number;
  finalUrl: string;
  contentType: string | null;
  bytes: Uint8Array;
  truncated: boolean;
}

class HttpStatusError extends Error {
  constructor(public status: number, public finalUrl: string, public blocked: string | null = null) {
    super(`HTTP ${status}`);
  }
}

const decoder = new TextDecoder("utf-8");

async function readCapped(res: Response, maxBytes: number, abort: Promise<never>): Promise<{ bytes: Uint8Array; truncated: boolean }> {
  if (!res.body) return { bytes: new Uint8Array(0), truncated: false };
  const reader = res.body.getReader();
  const chunks: Uint8Array[] = [];
  let total = 0;
  let truncated = false;
  try {
    for (;;) {
      const { done, value } = await Promise.race([reader.read(), abort]);
      if (done) break;
      if (!value) continue;
      if (total + value.length > maxBytes) {
        chunks.push(value.subarray(0, maxBytes - total));
        total = maxBytes;
        truncated = true;
        break;
      }
      chunks.push(value);
      total += value.length;
    }
  } finally {
    if (truncated) reader.cancel().catch(() => undefined);
    else reader.releaseLock?.();
  }
  const out = new Uint8Array(total);
  let o = 0;
  for (const c of chunks) {
    out.set(c, o);
    o += c.length;
  }
  return { bytes: out, truncated };
}

async function fetchOnce(url: string, o: Required<Pick<CheckOptions, "timeoutMs" | "maxBytes">> & CheckOptions): Promise<Fetched> {
  const f = o.fetch ?? (globalThis.fetch as typeof fetch | undefined);
  if (!f) throw Object.assign(new Error("no fetch available"), { code: "NO_FETCH" });
  const ctrl = new AbortController();
  let timer: ReturnType<typeof setTimeout> | undefined;
  const abort = new Promise<never>((_, reject) => {
    timer = setTimeout(() => {
      const e = new Error("timed out");
      e.name = "AbortError";
      ctrl.abort(e);
      reject(e);
    }, o.timeoutMs);
  });
  abort.catch(() => undefined);
  try {
    const headers: Record<string, string> = {
      "user-agent": o.userAgent ?? DEFAULT_USER_AGENT,
      accept: "text/html,application/xhtml+xml,application/pdf,text/plain;q=0.9,*/*;q=0.8",
      "accept-language": "en-US,en;q=0.9,ne;q=0.8",
      ...(o.headers ?? {}),
    };
    const res = await Promise.race([f(url, { redirect: "follow", headers, signal: ctrl.signal }), abort]);
    const finalUrl = res.url || url;
    if (res.status >= 400) {
      let blocked: string | null = null;
      if (res.status === 403 || res.status === 429 || res.status === 503) {
        // peek at (at most 64 KB of) the error page to tell a bot challenge from a plain refusal
        let body = "";
        try {
          const { bytes } = await readCapped(res, 64 * 1024, abort);
          body = decoder.decode(bytes);
        } catch {
          /* headers alone */
        }
        blocked = botBlockReason(res.status, res.headers, body);
      } else res.body?.cancel().catch(() => undefined);
      throw new HttpStatusError(res.status, finalUrl, blocked);
    }
    const { bytes, truncated } = await readCapped(res, o.maxBytes, abort);
    return { status: res.status, finalUrl, contentType: res.headers.get("content-type"), bytes, truncated };
  } finally {
    clearTimeout(timer);
  }
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/** Re-verify one source. Never throws. */
export async function check(item: WatchItem, opts: CheckOptions = {}): Promise<WatchResult> {
  const o = { ...DEFAULTS, ...opts };
  const t0 = Date.now();
  const base: WatchResult = { id: item.id, url: item.url, ok: false, found: false, matched: [], missing: [] };
  const allExpect = (Array.isArray(item.expect) ? item.expect : [item.expect]).map((e) => (typeof e === "string" ? e : String(e)));
  const fail = (r: Partial<WatchResult>): WatchResult => ({ ...base, missing: allExpect, ...r, ok: false, ms: Date.now() - t0 });

  let fetched: Fetched | undefined;
  for (let attempt = 0; ; attempt++) {
    try {
      fetched = await fetchOnce(item.url, o);
      break;
    } catch (err) {
      let r: Partial<WatchResult>;
      if (err instanceof HttpStatusError) {
        r = err.blocked
          ? { status: err.status, finalUrl: err.finalUrl, error: "bot_blocked", detail: err.blocked }
          : { status: err.status, finalUrl: err.finalUrl, error: err.status >= 500 ? "http_5xx" : "http_4xx", detail: `HTTP ${err.status}` };
      } else {
        const c = classifyError(err);
        r = { error: c.error, detail: c.detail, ...(c.tlsKind ? { tlsKind: c.tlsKind } : {}) };
      }
      const retryable = r.error === "timeout" || r.error === "http_5xx" || r.error === "network";
      if (retryable && attempt < Math.max(0, o.retries)) {
        if (o.retryDelayMs > 0) await sleep(o.retryDelayMs * (attempt + 1));
        continue;
      }
      return fail(r);
    }
  }

  const { status, finalUrl, contentType, bytes, truncated } = fetched;
  const kind = detectKind(item.kind, contentType, bytes, finalUrl);
  const meta: Partial<WatchResult> = { status, finalUrl, kind, bytes: bytes.length, truncated };

  let text = "";
  let title = "";
  let raw = "";
  let info: PdfInfo | undefined;
  try {
    if (kind === "html") {
      raw = decodeBytes(bytes, sniffCharset(bytes, contentType));
      title = htmlTitle(raw);
      text = htmlToText(raw);
    } else if (kind === "pdf") {
      info = await pdfInfo(bytes, { fixDevanagari: opts.pdf?.fixDevanagari !== false });
      text = info.text;
      meta.pdfQuality = qualityOf(info);
    } else text = await extractText(bytes, kind, contentType);
  } catch (err) {
    return fail({ ...meta, error: "unparseable", detail: String((err as Error)?.message ?? err).slice(0, 200) });
  }
  const norm = normalise(text);
  const contentHash = fnv1a64(norm);
  const hashMeta: Partial<WatchResult> = { contentHash, ...(item.prevHash !== undefined ? { changedSince: item.prevHash !== contentHash } : {}) };

  if (kind === "pdf" && norm.length === 0) {
    if (truncated) return fail({ ...meta, ...hashMeta, error: "too_large", detail: `PDF cut at ${bytes.length} bytes and no text recovered` });
    if (info?.imageOnly) {
      const n = info.images;
      return fail({ ...meta, ...hashMeta, error: "image_only", detail: `scanned/image-only PDF (${n} image${n === 1 ? "" : "s"}, no text) — needs OCR` });
    }
    return fail({
      ...meta,
      ...hashMeta,
      error: "unparseable",
      detail: info?.encrypted ? "encrypted PDF" : "no extractable text (encrypted, broken, or fonts without a Unicode map)",
    });
  }

  let haystack = norm;
  const transform = item.textTransform ?? opts.textTransform;
  if (transform) {
    try {
      const ctx = info
        ? { id: item.id, url: item.url, kind, fonts: info.fonts, ...(info.legacyFont ? { legacyFont: info.legacyFont } : {}) }
        : { id: item.id, url: item.url, kind };
      const t = normalise(await transform(text, ctx));
      if (t && t !== norm) haystack = `${t}\n\n${norm}`;
    } catch (err) {
      return fail({ ...meta, ...hashMeta, error: "unparseable", detail: `textTransform failed: ${String((err as Error)?.message ?? err).slice(0, 160)}` });
    }
  }
  const m = matchExpect(haystack, item.expect, item.match ?? "all");
  const res: WatchResult = {
    ...base,
    ...meta,
    ...hashMeta,
    found: m.found,
    matched: m.matched,
    missing: m.missing,
    ...(m.snippet ? { snippet: m.snippet } : {}),
  };

  if (kind === "html") {
    const app = jsAppReason(raw, text, o.minTextChars);
    if (app) {
      return { ...res, ok: false, error: "js_app", detail: `page renders with JavaScript; check its JSON API or use a headless browser (${app})`, ms: Date.now() - t0 };
    }
  }
  if (kind !== "pdf") {
    const why = placeholderReason(text, bytes.length, title, o.minTextChars);
    if (why) return { ...res, ok: false, error: "placeholder_page", detail: why, ms: Date.now() - t0 };
  }
  if (!m.found) return { ...res, ok: false, error: "not_found_text", detail: `missing: ${m.missing.join(", ")}`, ms: Date.now() - t0 };
  return { ...res, ok: true, ms: Date.now() - t0 };
}

function qualityOf(info: PdfInfo): PdfQuality {
  return {
    replacementChars: info.replacementChars,
    ...(info.legacyFont ? { legacyFont: info.legacyFont } : {}),
    fonts: info.fonts,
    images: info.images,
    ...(info.imageOnly ? { imageOnly: true } : {}),
    ...(info.ocrLayer ? { ocrLayer: true } : {}),
  };
}

function hostOf(url: string): string {
  try {
    return new URL(url).host.toLowerCase();
  } catch {
    return url;
  }
}

/**
 * Check many sources. Results come back in input order. At most `concurrency` (default 4) run at once,
 * and never more than one at a time against the same host.
 */
export async function checkAll(items: WatchItem[], opts: CheckOptions = {}): Promise<WatchResult[]> {
  const limit = Math.max(1, Math.floor(opts.concurrency ?? DEFAULTS.concurrency));
  const results: WatchResult[] = new Array(items.length);
  const pending = items.map((_, i) => i);
  const busy = new Set<string>();
  let running = 0;
  return new Promise((resolve) => {
    if (!items.length) return resolve(results);
    let finished = 0;
    const pump = () => {
      while (running < limit) {
        const k = pending.findIndex((i) => !busy.has(hostOf(items[i]!.url)));
        if (k < 0) break;
        const i = pending.splice(k, 1)[0]!;
        const host = hostOf(items[i]!.url);
        busy.add(host);
        running++;
        check(items[i]!, opts)
          .catch((err): WatchResult => ({ id: items[i]!.id, url: items[i]!.url, ok: false, found: false, matched: [], missing: [], error: "network", detail: String(err) }))
          .then((r) => {
            results[i] = r;
            busy.delete(host);
            running--;
            finished++;
            if (finished === items.length) resolve(results);
            else pump();
          });
      }
    };
    pump();
  });
}

/** Totals: ok / failed / changed and a count per error code. */
export function summarize(results: WatchResult[]): Summary {
  const byError: Partial<Record<WatchError, number>> = {};
  let ok = 0;
  let changed = 0;
  for (const r of results) {
    if (r.ok) ok++;
    if (r.changedSince) changed++;
    if (r.error) byError[r.error] = (byError[r.error] ?? 0) + 1;
  }
  return { total: results.length, ok, failed: results.length - ok, changed, byError };
}
