import { decodeBytes, htmlTitle, htmlToText, sniffCharset } from "./html";
import { fnv1a64, matchExpect, normalise } from "./normalise";
import { isPdf, pdfText } from "./pdf";
import type { CheckOptions, Kind, Summary, TlsKind, WatchError, WatchItem, WatchResult } from "./types";

/** Default User-Agent: a current desktop Chrome (some government sites block unknown agents). */
export const DEFAULT_USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36";

const DEFAULTS = {
  timeoutMs: 15000,
  maxBytes: 10 * 1024 * 1024,
  concurrency: 4,
  retries: 1,
  retryDelayMs: 500,
  minTextChars: 200,
};

// ---------------------------------------------------------------- errors

const TLS_CHAIN = new Set(["UNABLE_TO_VERIFY_LEAF_SIGNATURE", "UNABLE_TO_GET_ISSUER_CERT", "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"]);
const TLS_EXPIRED = new Set(["CERT_HAS_EXPIRED", "CERT_NOT_YET_VALID"]);
const TLS_SELF = new Set(["DEPTH_ZERO_SELF_SIGNED_CERT", "SELF_SIGNED_CERT_IN_CHAIN"]);
const TLS_HOST = new Set(["ERR_TLS_CERT_ALTNAME_INVALID"]);
const TLS_RE = /^(CERT_|UNABLE_TO_VERIFY_LEAF_SIGNATURE|UNABLE_TO_GET_ISSUER_CERT|ERR_TLS_|ERR_SSL_|SELF_SIGNED_|DEPTH_ZERO_|UNABLE_TO_DECRYPT_CERT|UNABLE_TO_DECODE_ISSUER|INVALID_CA|PATH_LENGTH_EXCEEDED|INVALID_PURPOSE|CERT_UNTRUSTED|CERT_REJECTED|HOSTNAME_MISMATCH)/;
const DNS = new Set(["ENOTFOUND", "EAI_AGAIN", "EAI_NONAME", "EAI_NODATA", "EAI_FAIL"]);
const TIMEOUTS = new Set(["ETIMEDOUT", "UND_ERR_CONNECT_TIMEOUT", "UND_ERR_HEADERS_TIMEOUT", "UND_ERR_BODY_TIMEOUT", "ABORT_ERR"]);

/** The sub-class of a TLS error code. */
export function tlsKindOf(code: string): TlsKind {
  if (TLS_CHAIN.has(code)) return "chain";
  if (TLS_EXPIRED.has(code)) return "expired";
  if (TLS_SELF.has(code)) return "self_signed";
  if (TLS_HOST.has(code)) return "hostname";
  return "other";
}

function findCode(err: unknown): string | undefined {
  let e: any = err;
  for (let i = 0; i < 6 && e; i++) {
    if (typeof e.code === "string" && e.code !== "ERR_INVALID_STATE") return e.code;
    if (Array.isArray(e.errors) && e.errors[0]) {
      const c = findCode(e.errors[0]);
      if (c) return c;
    }
    e = e.cause;
  }
  return undefined;
}

/** Classify a thrown fetch error. */
export function classifyError(err: unknown): { error: WatchError; tlsKind?: TlsKind; detail: string } {
  const e: any = err;
  const name: string = e?.name ?? "";
  const msg: string = String(e?.cause?.message ?? e?.message ?? e ?? "");
  const code = findCode(err);
  if (name === "AbortError" || name === "TimeoutError" || e?.cause?.name === "AbortError" || e?.cause?.name === "TimeoutError")
    return { error: "timeout", detail: code ?? name };
  if (code) {
    if (TLS_RE.test(code)) return { error: "tls", tlsKind: tlsKindOf(code), detail: code };
    if (DNS.has(code)) return { error: "dns", detail: code };
    if (TIMEOUTS.has(code)) return { error: "timeout", detail: code };
    if (code === "EPROTO" && /ssl|tls/i.test(msg)) return { error: "tls", tlsKind: "other", detail: `${code}: ${msg}`.slice(0, 200) };
    return { error: "network", detail: code };
  }
  if (/certificate|ssl|tls/i.test(msg)) return { error: "tls", tlsKind: "other", detail: msg.slice(0, 200) };
  if (/getaddrinfo|ENOTFOUND|name not resolved/i.test(msg)) return { error: "dns", detail: msg.slice(0, 200) };
  return { error: "network", detail: msg.slice(0, 200) || "fetch failed" };
}

// ---------------------------------------------------------------- placeholder

const PLACEHOLDER_PATTERNS: RegExp[] = [
  /^\s*this is (a )?test\b/i,
  /^\s*test( page)?\s*$/i,
  /\bcoming soon\b/i,
  /\bunder construction\b/i,
  /^\s*it works!?/i,
  /\bwelcome to nginx\b/i,
  /\bapache2? (ubuntu |debian )?default page\b/i,
  /\btest page for the (apache|nginx)/i,
  /^\s*index of \//i,
  /\bdefault web site page\b/i,
  /\bweb server'?s default page\b/i,
  /\bthis page is (auto)?generated by plesk\b/i,
  /\bthere is no web ?site configured at this address\b/i,
  /\bfuture home of something quite cool\b/i,
  /\bcpanel\b.{0,80}\b(default|account (has been )?suspended)/i,
  /\b(site|website) is (currently )?(under|down for) maintenance\b/i,
  /\baccount (has been )?suspended\b/i,
  /\bthis (domain|site) (has expired|is parked|is for sale)\b/i,
  /^\s*iis windows server\b/i,
];

/** Why a page looks like a placeholder, or null. `title` is checked alongside the visible text. */
export function placeholderReason(text: string, bytes: number, title = "", minTextChars = DEFAULTS.minTextChars): string | null {
  const t = normalise(text);
  const short = t.length < 3000;
  if (short) {
    for (const re of PLACEHOLDER_PATTERNS) {
      if (re.test(t.slice(0, 400)) || (title && re.test(normalise(title)))) return `matches ${re.source}`;
    }
  }
  if (bytes < minTextChars || t.length < minTextChars) return `only ${t.length} chars of visible text`;
  return null;
}

/**
 * Is this a placeholder page? Visible text shorter than 200 chars (or a body under 200 bytes),
 * or a short page reading like a test page, default server page, "coming soon", maintenance or suspended account.
 */
export function isPlaceholder(text: string, bytes: number = text.length): boolean {
  return placeholderReason(text, bytes) !== null;
}

// ---------------------------------------------------------------- extraction

function detectKind(declared: WatchItem["kind"], contentType: string | null, bytes: Uint8Array, url: string): Kind {
  if (declared && declared !== "auto") return declared;
  const ct = (contentType ?? "").toLowerCase();
  if (ct.includes("application/pdf") || ct.includes("application/x-pdf")) return "pdf";
  if (ct.includes("html") || ct.includes("xml")) return isPdf(bytes) ? "pdf" : "html";
  if (ct.startsWith("text/plain")) return "text";
  if (isPdf(bytes)) return "pdf";
  let path = url;
  try {
    path = new URL(url).pathname;
  } catch {
    /* relative or odd */
  }
  if (/\.pdf$/i.test(path)) return "pdf";
  if (/\.(txt|csv)$/i.test(path)) return "text";
  return "html";
}

/**
 * Extract visible text. `html`: tags/scripts dropped, entities decoded, charset sniffed.
 * `text`: decoded as-is. `pdf`: {@link pdfText}. Strings are taken as already-decoded.
 */
export async function extractText(input: Uint8Array | string, kind: Kind, contentType?: string | null): Promise<string> {
  if (kind === "pdf") {
    const bytes = typeof input === "string" ? Uint8Array.from(input, (c) => c.charCodeAt(0) & 255) : input;
    return pdfText(bytes);
  }
  const raw = typeof input === "string" ? input : decodeBytes(input, sniffCharset(input, contentType));
  return kind === "html" ? htmlToText(raw) : raw;
}

// ---------------------------------------------------------------- fetch

interface Fetched {
  status: number;
  finalUrl: string;
  contentType: string | null;
  bytes: Uint8Array;
  truncated: boolean;
}

class HttpStatusError extends Error {
  constructor(public status: number, public finalUrl: string) {
    super(`HTTP ${status}`);
  }
}

async function readCapped(res: Response, maxBytes: number, abort: Promise<never>): Promise<{ bytes: Uint8Array; truncated: boolean }> {
  if (!res.body) return { bytes: new Uint8Array(0), truncated: false };
  const reader = res.body.getReader();
  const chunks: Uint8Array[] = [];
  let total = 0;
  let truncated = false;
  try {
    for (;;) {
      const { done, value } = await Promise.race([reader.read(), abort]);
      if (done) break;
      if (!value) continue;
      if (total + value.length > maxBytes) {
        chunks.push(value.subarray(0, maxBytes - total));
        total = maxBytes;
        truncated = true;
        break;
      }
      chunks.push(value);
      total += value.length;
    }
  } finally {
    if (truncated) reader.cancel().catch(() => undefined);
    else reader.releaseLock?.();
  }
  const out = new Uint8Array(total);
  let o = 0;
  for (const c of chunks) {
    out.set(c, o);
    o += c.length;
  }
  return { bytes: out, truncated };
}

async function fetchOnce(url: string, o: Required<Pick<CheckOptions, "timeoutMs" | "maxBytes">> & CheckOptions): Promise<Fetched> {
  const f = o.fetch ?? (globalThis.fetch as typeof fetch | undefined);
  if (!f) throw Object.assign(new Error("no fetch available"), { code: "NO_FETCH" });
  const ctrl = new AbortController();
  let timer: ReturnType<typeof setTimeout> | undefined;
  const abort = new Promise<never>((_, reject) => {
    timer = setTimeout(() => {
      const e = new Error("timed out");
      e.name = "AbortError";
      ctrl.abort(e);
      reject(e);
    }, o.timeoutMs);
  });
  abort.catch(() => undefined);
  try {
    const headers: Record<string, string> = {
      "user-agent": o.userAgent ?? DEFAULT_USER_AGENT,
      accept: "text/html,application/xhtml+xml,application/pdf,text/plain;q=0.9,*/*;q=0.8",
      "accept-language": "en-US,en;q=0.9,ne;q=0.8",
      ...(o.headers ?? {}),
    };
    const res = await Promise.race([f(url, { redirect: "follow", headers, signal: ctrl.signal }), abort]);
    const finalUrl = res.url || url;
    if (res.status >= 400) {
      res.body?.cancel().catch(() => undefined);
      throw new HttpStatusError(res.status, finalUrl);
    }
    const { bytes, truncated } = await readCapped(res, o.maxBytes, abort);
    return { status: res.status, finalUrl, contentType: res.headers.get("content-type"), bytes, truncated };
  } finally {
    clearTimeout(timer);
  }
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/** Re-verify one source. Never throws. */
export async function check(item: WatchItem, opts: CheckOptions = {}): Promise<WatchResult> {
  const o = { ...DEFAULTS, ...opts };
  const t0 = Date.now();
  const base: WatchResult = { id: item.id, url: item.url, ok: false, found: false, matched: [], missing: [] };
  const allExpect = (Array.isArray(item.expect) ? item.expect : [item.expect]).map((e) => (typeof e === "string" ? e : String(e)));
  const fail = (r: Partial<WatchResult>): WatchResult => ({ ...base, missing: allExpect, ...r, ok: false, ms: Date.now() - t0 });

  let fetched: Fetched | undefined;
  for (let attempt = 0; ; attempt++) {
    try {
      fetched = await fetchOnce(item.url, o);
      break;
    } catch (err) {
      let r: Partial<WatchResult>;
      if (err instanceof HttpStatusError) {
        r = { status: err.status, finalUrl: err.finalUrl, error: err.status >= 500 ? "http_5xx" : "http_4xx", detail: `HTTP ${err.status}` };
      } else {
        const c = classifyError(err);
        r = { error: c.error, detail: c.detail, ...(c.tlsKind ? { tlsKind: c.tlsKind } : {}) };
      }
      const retryable = r.error === "timeout" || r.error === "http_5xx" || r.error === "network";
      if (retryable && attempt < Math.max(0, o.retries)) {
        if (o.retryDelayMs > 0) await sleep(o.retryDelayMs * (attempt + 1));
        continue;
      }
      return fail(r);
    }
  }

  const { status, finalUrl, contentType, bytes, truncated } = fetched;
  const kind = detectKind(item.kind, contentType, bytes, finalUrl);
  const meta: Partial<WatchResult> = { status, finalUrl, kind, bytes: bytes.length, truncated };

  let text = "";
  let title = "";
  try {
    if (kind === "html") {
      const raw = decodeBytes(bytes, sniffCharset(bytes, contentType));
      title = htmlTitle(raw);
      text = htmlToText(raw);
    } else text = await extractText(bytes, kind, contentType);
  } catch (err) {
    return fail({ ...meta, error: "unparseable", detail: String((err as Error)?.message ?? err).slice(0, 200) });
  }
  const norm = normalise(text);
  const contentHash = fnv1a64(norm);
  const hashMeta: Partial<WatchResult> = { contentHash, ...(item.prevHash !== undefined ? { changedSince: item.prevHash !== contentHash } : {}) };

  if (kind === "pdf" && norm.length === 0) {
    return fail({
      ...meta,
      ...hashMeta,
      error: truncated ? "too_large" : "unparseable",
      detail: truncated
        ? `PDF cut at ${bytes.length} bytes and no text recovered`
        : "no extractable text (scanned image, encrypted, or fonts without a Unicode map)",
    });
  }

  let haystack = norm;
  const transform = item.textTransform ?? opts.textTransform;
  if (transform) {
    try {
      const t = normalise(await transform(text, { id: item.id, url: item.url, kind }));
      if (t && t !== norm) haystack = `${t}\n\n${norm}`;
    } catch (err) {
      return fail({ ...meta, ...hashMeta, error: "unparseable", detail: `textTransform failed: ${String((err as Error)?.message ?? err).slice(0, 160)}` });
    }
  }
  const m = matchExpect(haystack, item.expect, item.match ?? "all");
  const res: WatchResult = {
    ...base,
    ...meta,
    ...hashMeta,
    found: m.found,
    matched: m.matched,
    missing: m.missing,
    ...(m.snippet ? { snippet: m.snippet } : {}),
  };

  if (kind !== "pdf") {
    const why = placeholderReason(text, bytes.length, title, o.minTextChars);
    if (why) return { ...res, ok: false, error: "placeholder_page", detail: why, ms: Date.now() - t0 };
  }
  if (!m.found) return { ...res, ok: false, error: "not_found_text", detail: `missing: ${m.missing.join(", ")}`, ms: Date.now() - t0 };
  return { ...res, ok: true, ms: Date.now() - t0 };
}

function hostOf(url: string): string {
  try {
    return new URL(url).host.toLowerCase();
  } catch {
    return url;
  }
}

/**
 * Check many sources. Results come back in input order. At most `concurrency` (default 4) run at once,
 * and never more than one at a time against the same host.
 */
export async function checkAll(items: WatchItem[], opts: CheckOptions = {}): Promise<WatchResult[]> {
  const limit = Math.max(1, Math.floor(opts.concurrency ?? DEFAULTS.concurrency));
  const results: WatchResult[] = new Array(items.length);
  const pending = items.map((_, i) => i);
  const busy = new Set<string>();
  let running = 0;
  return new Promise((resolve) => {
    if (!items.length) return resolve(results);
    let finished = 0;
    const pump = () => {
      while (running < limit) {
        const k = pending.findIndex((i) => !busy.has(hostOf(items[i]!.url)));
        if (k < 0) break;
        const i = pending.splice(k, 1)[0]!;
        const host = hostOf(items[i]!.url);
        busy.add(host);
        running++;
        check(items[i]!, opts)
          .catch((err): WatchResult => ({ id: items[i]!.id, url: items[i]!.url, ok: false, found: false, matched: [], missing: [], error: "network", detail: String(err) }))
          .then((r) => {
            results[i] = r;
            busy.delete(host);
            running--;
            finished++;
            if (finished === items.length) resolve(results);
            else pump();
          });
      }
    };
    pump();
  });
}

/** Totals: ok / failed / changed and a count per error code. */
export function summarize(results: WatchResult[]): Summary {
  const byError: Partial<Record<WatchError, number>> = {};
  let ok = 0;
  let changed = 0;
  for (const r of results) {
    if (r.ok) ok++;
    if (r.changedSince) changed++;
    if (r.error) byError[r.error] = (byError[r.error] ?? 0) + 1;
  }
  return { total: results.length, ok, failed: results.length - ok, changed, byError };
}
