/**
 * ISO 4217 active currencies: [code, numeric, minor units, name, symbol].
 * Minor units follow the ISO list (not ICU cash rounding). Symbols are the
 * common local sign where one exists, else "". ANG is not listed: it was
 * replaced by XCG (which inherited numeric 532) in 2025.
 */
export type Row = readonly [string, string, number, string, string];

export const ROWS: readonly Row[] = [
  ["AED", "784", 2, "UAE Dirham", "د.إ"],
  ["AFN", "971", 2, "Afghani", "؋"],
  ["ALL", "008", 2, "Lek", "L"],
  ["AMD", "051", 2, "Armenian Dram", "֏"],
  ["AOA", "973", 2, "Kwanza", "Kz"],
  ["ARS", "032", 2, "Argentine Peso", "$"],
  ["AUD", "036", 2, "Australian Dollar", "$"],
  ["AWG", "533", 2, "Aruban Florin", "ƒ"],
  ["AZN", "944", 2, "Azerbaijan Manat", "₼"],
  ["BAM", "977", 2, "Convertible Mark", "KM"],
  ["BBD", "052", 2, "Barbados Dollar", "$"],
  ["BDT", "050", 2, "Taka", "৳"],
  ["BGN", "975", 2, "Bulgarian Lev", "лв"],
  ["BHD", "048", 3, "Bahraini Dinar", ".د.ب"],
  ["BIF", "108", 0, "Burundi Franc", "FBu"],
  ["BMD", "060", 2, "Bermudian Dollar", "$"],
  ["BND", "096", 2, "Brunei Dollar", "$"],
  ["BOB", "068", 2, "Boliviano", "Bs."],
  ["BOV", "984", 2, "Mvdol", ""],
  ["BRL", "986", 2, "Brazilian Real", "R$"],
  ["BSD", "044", 2, "Bahamian Dollar", "$"],
  ["BTN", "064", 2, "Ngultrum", "Nu."],
  ["BWP", "072", 2, "Pula", "P"],
  ["BYN", "933", 2, "Belarusian Ruble", "Br"],
  ["BZD", "084", 2, "Belize Dollar", "$"],
  ["CAD", "124", 2, "Canadian Dollar", "$"],
  ["CDF", "976", 2, "Congolese Franc", "FC"],
  ["CHE", "947", 2, "WIR Euro", ""],
  ["CHF", "756", 2, "Swiss Franc", "CHF"],
  ["CHW", "948", 2, "WIR Franc", ""],
  ["CLF", "990", 4, "Unidad de Fomento", "UF"],
  ["CLP", "152", 0, "Chilean Peso", "$"],
  ["CNY", "156", 2, "Yuan Renminbi", "¥"],
  ["COP", "170", 2, "Colombian Peso", "$"],
  ["COU", "970", 2, "Unidad de Valor Real", ""],
  ["CRC", "188", 2, "Costa Rican Colon", "₡"],
  ["CUP", "192", 2, "Cuban Peso", "$"],
  ["CVE", "132", 2, "Cabo Verde Escudo", "$"],
  ["CZK", "203", 2, "Czech Koruna", "Kč"],
  ["DJF", "262", 0, "Djibouti Franc", "Fdj"],
  ["DKK", "208", 2, "Danish Krone", "kr"],
  ["DOP", "214", 2, "Dominican Peso", "RD$"],
  ["DZD", "012", 2, "Algerian Dinar", "د.ج"],
  ["EGP", "818", 2, "Egyptian Pound", "E£"],
  ["ERN", "232", 2, "Nakfa", "Nfk"],
  ["ETB", "230", 2, "Ethiopian Birr", "Br"],
  ["EUR", "978", 2, "Euro", "€"],
  ["FJD", "242", 2, "Fiji Dollar", "$"],
  ["FKP", "238", 2, "Falkland Islands Pound", "£"],
  ["GBP", "826", 2, "Pound Sterling", "£"],
  ["GEL", "981", 2, "Lari", "₾"],
  ["GHS", "936", 2, "Ghana Cedi", "₵"],
  ["GIP", "292", 2, "Gibraltar Pound", "£"],
  ["GMD", "270", 2, "Dalasi", "D"],
  ["GNF", "324", 0, "Guinean Franc", "FG"],
  ["GTQ", "320", 2, "Quetzal", "Q"],
  ["GYD", "328", 2, "Guyana Dollar", "$"],
  ["HKD", "344", 2, "Hong Kong Dollar", "HK$"],
  ["HNL", "340", 2, "Lempira", "L"],
  ["HTG", "332", 2, "Gourde", "G"],
  ["HUF", "348", 2, "Forint", "Ft"],
  ["IDR", "360", 2, "Rupiah", "Rp"],
  ["ILS", "376", 2, "New Israeli Sheqel", "₪"],
  ["INR", "356", 2, "Indian Rupee", "₹"],
  ["IQD", "368", 3, "Iraqi Dinar", "ع.د"],
  ["IRR", "364", 2, "Iranian Rial", "﷼"],
  ["ISK", "352", 0, "Iceland Krona", "kr"],
  ["JMD", "388", 2, "Jamaican Dollar", "$"],
  ["JOD", "400", 3, "Jordanian Dinar", "د.أ"],
  ["JPY", "392", 0, "Yen", "¥"],
  ["KES", "404", 2, "Kenyan Shilling", "KSh"],
  ["KGS", "417", 2, "Som", "с"],
  ["KHR", "116", 2, "Riel", "៛"],
  ["KMF", "174", 0, "Comorian Franc", "CF"],
  ["KPW", "408", 2, "North Korean Won", "₩"],
  ["KRW", "410", 0, "Won", "₩"],
  ["KWD", "414", 3, "Kuwaiti Dinar", "د.ك"],
  ["KYD", "136", 2, "Cayman Islands Dollar", "$"],
  ["KZT", "398", 2, "Tenge", "₸"],
  ["LAK", "418", 2, "Lao Kip", "₭"],
  ["LBP", "422", 2, "Lebanese Pound", "ل.ل"],
  ["LKR", "144", 2, "Sri Lanka Rupee", "Rs"],
  ["LRD", "430", 2, "Liberian Dollar", "$"],
  ["LSL", "426", 2, "Loti", "L"],
  ["LYD", "434", 3, "Libyan Dinar", "ل.د"],
  ["MAD", "504", 2, "Moroccan Dirham", "د.م."],
  ["MDL", "498", 2, "Moldovan Leu", "L"],
  ["MGA", "969", 2, "Malagasy Ariary", "Ar"],
  ["MKD", "807", 2, "Denar", "ден"],
  ["MMK", "104", 2, "Kyat", "K"],
  ["MNT", "496", 2, "Tugrik", "₮"],
  ["MOP", "446", 2, "Pataca", "MOP$"],
  ["MRU", "929", 2, "Ouguiya", "UM"],
  ["MUR", "480", 2, "Mauritius Rupee", "₨"],
  ["MVR", "462", 2, "Rufiyaa", "Rf"],
  ["MWK", "454", 2, "Malawi Kwacha", "MK"],
  ["MXN", "484", 2, "Mexican Peso", "$"],
  ["MXV", "979", 2, "Mexican Unidad de Inversion (UDI)", ""],
  ["MYR", "458", 2, "Malaysian Ringgit", "RM"],
  ["MZN", "943", 2, "Mozambique Metical", "MT"],
  ["NAD", "516", 2, "Namibia Dollar", "$"],
  ["NGN", "566", 2, "Naira", "₦"],
  ["NIO", "558", 2, "Cordoba Oro", "C$"],
  ["NOK", "578", 2, "Norwegian Krone", "kr"],
  ["NPR", "524", 2, "Nepalese Rupee", "रू"],
  ["NZD", "554", 2, "New Zealand Dollar", "$"],
  ["OMR", "512", 3, "Rial Omani", "ر.ع."],
  ["PAB", "590", 2, "Balboa", "B/."],
  ["PEN", "604", 2, "Sol", "S/"],
  ["PGK", "598", 2, "Kina", "K"],
  ["PHP", "608", 2, "Philippine Peso", "₱"],
  ["PKR", "586", 2, "Pakistan Rupee", "₨"],
  ["PLN", "985", 2, "Zloty", "zł"],
  ["PYG", "600", 0, "Guarani", "₲"],
  ["QAR", "634", 2, "Qatari Rial", "ر.ق"],
  ["RON", "946", 2, "Romanian Leu", "lei"],
  ["RSD", "941", 2, "Serbian Dinar", "дин."],
  ["RUB", "643", 2, "Russian Ruble", "₽"],
  ["RWF", "646", 0, "Rwanda Franc", "FRw"],
  ["SAR", "682", 2, "Saudi Riyal", "﷼"],
  ["SBD", "090", 2, "Solomon Islands Dollar", "$"],
  ["SCR", "690", 2, "Seychelles Rupee", "₨"],
  ["SDG", "938", 2, "Sudanese Pound", "ج.س."],
  ["SEK", "752", 2, "Swedish Krona", "kr"],
  ["SGD", "702", 2, "Singapore Dollar", "$"],
  ["SHP", "654", 2, "Saint Helena Pound", "£"],
  ["SLE", "925", 2, "Leone", "Le"],
  ["SOS", "706", 2, "Somali Shilling", "Sh"],
  ["SRD", "968", 2, "Surinam Dollar", "$"],
  ["SSP", "728", 2, "South Sudanese Pound", "£"],
  ["STN", "930", 2, "Dobra", "Db"],
  ["SVC", "222", 2, "El Salvador Colon", "₡"],
  ["SYP", "760", 2, "Syrian Pound", "£S"],
  ["SZL", "748", 2, "Lilangeni", "E"],
  ["THB", "764", 2, "Baht", "฿"],
  ["TJS", "972", 2, "Somoni", "SM"],
  ["TMT", "934", 2, "Turkmenistan New Manat", "m"],
  ["TND", "788", 3, "Tunisian Dinar", "د.ت"],
  ["TOP", "776", 2, "Pa'anga", "T$"],
  ["TRY", "949", 2, "Turkish Lira", "₺"],
  ["TTD", "780", 2, "Trinidad and Tobago Dollar", "TT$"],
  ["TWD", "901", 2, "New Taiwan Dollar", "NT$"],
  ["TZS", "834", 2, "Tanzanian Shilling", "TSh"],
  ["UAH", "980", 2, "Hryvnia", "₴"],
  ["UGX", "800", 0, "Uganda Shilling", "USh"],
  ["USD", "840", 2, "US Dollar", "$"],
  ["USN", "997", 2, "US Dollar (Next day)", ""],
  ["UYI", "940", 0, "Uruguay Peso en Unidades Indexadas (UI)", ""],
  ["UYU", "858", 2, "Peso Uruguayo", "$U"],
  ["UYW", "927", 4, "Unidad Previsional", ""],
  ["UZS", "860", 2, "Uzbekistan Sum", "so'm"],
  ["VED", "926", 2, "Bolívar Soberano", "Bs.D"],
  ["VES", "928", 2, "Bolívar Soberano", "Bs.S"],
  ["VND", "704", 0, "Dong", "₫"],
  ["VUV", "548", 0, "Vatu", "VT"],
  ["WST", "882", 2, "Tala", "WS$"],
  ["XAF", "950", 0, "CFA Franc BEAC", "FCFA"],
  ["XAG", "961", -1, "Silver", ""],
  ["XAU", "959", -1, "Gold", ""],
  ["XBA", "955", -1, "Bond Markets Unit European Composite Unit (EURCO)", ""],
  ["XBB", "956", -1, "Bond Markets Unit European Monetary Unit (E.M.U.-6)", ""],
  ["XBC", "957", -1, "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", ""],
  ["XBD", "958", -1, "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", ""],
  ["XCD", "951", 2, "East Caribbean Dollar", "$"],
  ["XCG", "532", 2, "Caribbean Guilder", "Cg"],
  ["XDR", "960", -1, "SDR (Special Drawing Right)", ""],
  ["XOF", "952", 0, "CFA Franc BCEAO", "CFA"],
  ["XPD", "964", -1, "Palladium", ""],
  ["XPF", "953", 0, "CFP Franc", "₣"],
  ["XPT", "962", -1, "Platinum", ""],
  ["XSU", "994", -1, "Sucre", ""],
  ["XTS", "963", -1, "Codes specifically reserved for testing purposes", ""],
  ["XUA", "965", -1, "ADB Unit of Account", ""],
  ["XXX", "999", -1, "The codes assigned for transactions where no currency is involved", ""],
  ["YER", "886", 2, "Yemeni Rial", "﷼"],
  ["ZAR", "710", 2, "Rand", "R"],
  ["ZMW", "967", 2, "Zambian Kwacha", "ZK"],
  ["ZWG", "924", 2, "Zimbabwe Gold", "ZiG"],
];
