/**
 * Arithmetic over the Galois field GF(256) used by QR-code Reed–Solomon error
 * correction. The field is generated by the primitive polynomial
 * `x^8 + x^4 + x^3 + x^2 + 1` (0x11D) with 2 as a generator element — exactly
 * as specified by ISO/IEC 18004. Everything here is hand-written and
 * dependency-free.
 */

/** The QR primitive polynomial (x^8 + x^4 + x^3 + x^2 + 1). */
export const GF_PRIMITIVE = 0x11d;

// Precompute exp/log tables. EXP is doubled (length 512) so that
// EXP[a + b] never needs a modulo when multiplying via logarithms.
const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);

(() => {
  let x = 1;
  for (let i = 0; i < 255; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= GF_PRIMITIVE;
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255]!;
})();

/** `EXP[i]` = the field element α^i (α = 2). Table is doubled to length 512. */
export function gfExp(i: number): number {
  return EXP[((i % 255) + 255) % 255]!;
}

/** `LOG[x]` = the exponent e such that α^e = x. Undefined for 0. */
export function gfLog(x: number): number {
  if (x === 0) throw new Error("gfLog(0) is undefined");
  return LOG[x]!;
}

/** Multiply two field elements. */
export function gfMul(a: number, b: number): number {
  if (a === 0 || b === 0) return 0;
  return EXP[LOG[a]! + LOG[b]!]!;
}

/** Raise a field element to an integer power. */
export function gfPow(a: number, n: number): number {
  if (a === 0) return n === 0 ? 1 : 0;
  return EXP[(((LOG[a]! * n) % 255) + 255 * 256) % 255]!;
}

/**
 * Compute the Reed–Solomon generator (divisor) polynomial of the given degree.
 * Returns `degree` coefficients for x^(degree-1) … x^0 (the leading x^degree
 * coefficient is an implicit 1). This matches the QR standard generators.
 */
export function rsComputeDivisor(degree: number): Uint8Array {
  if (degree < 1 || degree > 255) throw new Error("degree out of range");
  const result = new Uint8Array(degree);
  result[degree - 1] = 1; // start with the monomial x^0
  // Multiply by (x - α^i) for i = 0 … degree-1.
  let root = 1;
  for (let i = 0; i < degree; i++) {
    for (let j = 0; j < degree; j++) {
      result[j] = gfMul(result[j]!, root);
      if (j + 1 < degree) result[j]! ^= result[j + 1]!;
    }
    root = gfMul(root, 0x02);
  }
  return result;
}

/**
 * Compute the Reed–Solomon error-correction codewords (the remainder) for a
 * block of data codewords against a precomputed divisor.
 */
export function rsComputeRemainder(data: Uint8Array | number[], divisor: Uint8Array): Uint8Array {
  const degree = divisor.length;
  const result = new Uint8Array(degree);
  for (let d = 0; d < data.length; d++) {
    const factor = data[d]! ^ result[0]!;
    // Shift the running remainder left by one and append a zero.
    result.copyWithin(0, 1);
    result[degree - 1] = 0;
    for (let i = 0; i < degree; i++) result[i]! ^= gfMul(divisor[i]!, factor);
  }
  return result;
}
